#!/bin/bash
#################################
# ----------------------------- #
#         Easy Gentoo           #
# ----------------------------- #
# a small Gentoo install script #
#              by               #
#        Şehidcan Erdim         #
# sehidcan (at) gmail (dot) com #
#################################

normal=$'\e[0m'; red=$'\e[31;01m'; green=$'\e[32;01m'; yellow=$'\e[33;01m'; blue=$'\e[34;01m'; pink=$'\e[35;01m'; cyan=$'\e[36;01m'; white=$'\e[37;01m'

en() { echo "${normal}${*}${normal}";} ; er() { echo "${red}${*}${normal}";} ; eg() { echo "${green}${*}${normal}";} ; ey() { echo "${yellow}${*}${normal}";}
eb() { echo "${blue}${*}${normal}";} ; ep() { echo "${pink}${*}${normal}";} ; ec() { echo "${cyan}${*}${normal}";} ; ew() { echo "${white}${*}${normal}";}

en2() { echo -n "${normal}${*}${normal}";} ; er2() { echo -n "${red}${*}${normal}";} ; eg2() { echo -n "${green}${*}${normal}";} ; ey2() { echo -n "${yellow}${*}${normal}";}
eb2() { echo -n "${blue}${*}${normal}";} ; ep2() { echo -n "${pink}${*}${normal}";} ; ec2() { echo -n "${cyan}${*}${normal}";} ; ew2() { echo -n "${white}${*}${normal}";}

cl() { clear; sleep 0.5s; echo;}

exist() {
    which ${1} &>/dev/null && { ey2 "  * "; eb2 "${1}"; en " exists"; sleep 0.2s; } || { er2 "  * "; eb2 "${1}"; er " doesn't exist"; er "Some tools are missing - Please use a different install media/environment"; echo; exit 1; }
}

find_flags() {
    cpu_inst="$(grep flags /proc/cpuinfo | uniq | tr -s '[:blank:]' ' ' | cut -d':' -f2)"
    flags_list="3dnow 3dnowext mmx mmxext sse sse2 sse3 sse4 sse4a sse4_1 sse4_2 sse5 ssse3"

    for v in ${flags_list}
    do
        echo "${cpu_inst}" | grep -o -w "${v}" >> flags.eg
    done

    echo "${cpu_inst}" | grep -o -w "pni" &>/dev/null && echo "sse3" >> flags.eg

    a2v "available_cpu_flags=\"$(tr '\n' ' ' < flags.eg | sed -e 's:^[ \t]*::' -e 's:[ \t]*$::')\""
}

fl() {
    trg_file="${1}"
    
    mkdir -p "$(dirname ${trg_file})"
    
    if [ -e "${trg_file}" ]; then
        case ${2} in
        b)
            cp "${trg_file}" "${trg_file}".backup
        ;;
        esac
        
        case ${3} in
        d)
            rm -rf "${trg_file}"
        ;;
        esac
    else
        touch "${trg_file}"
    fi
}

avoid_dup() {
    if [ -n "${@}" ] && [ -n "${trg_file}" ]; then
        allofit="${@}"
        nameonly="$(echo ${allofit} | cut -d'=' -f1)"
        if [ -n "$(grep ^${nameonly} ${trg_file})" ];then
            sed -i s:"^${nameonly}=.*":"${allofit}": ${trg_file}
        else
            echo "${allofit}" >> ${trg_file}
        fi
    fi
}

avoid_dup_kernel() {
    if [ -n "${@}" ] && [ -n "${trg_file}" ]; then
        allofit="${@}"
        nameonly="$(echo ${allofit} | cut -d'=' -f1)"
        sed -i "\!^#.*${nameonly}.*!d" ${trg_file}
        sed -i "\!^${nameonly}=.*!d" ${trg_file}
        echo "${allofit}" >> ${trg_file}
    fi
}

cf() {
    [[ -n "${trg_file}" ]] && echo "$@" >> ${trg_file}
}

a2v() {
    echo "export $@" >> "${vl}"; vlist
}

csum() {
    md5sum -c $1
    case $? in
    0)
        check="ok"; csn="1"; sleep 1s
    ;;
    *)
        ((csn++))
        case ${csn} in
        3)
            echo; er "  Looks like the server has a corrupted version of the file or there is a technical problem."
            echo; er2 "  Press "; eg2 "c"; er " to ignore and try again."
            eg2 "s"; er " to cancel setup..."; echo
            
            while true
            do
                read -n1 islem
                case ${islem} in
                c)
                    check="ok"; csn="1"; break
                ;;
                s)
                    exit 1
                ;;
                esac
            done
        ;;
        *)
            check="x"; rm -rf $2; echo; er "  File is outdated or corrupted."
        esac
    ;;
    esac
}

shasum() {
    sha512sum -c $1
    case $? in
    0)
        check="ok"; ssn="1"; sleep 1s
    ;;
    *)
        ((ssn++))
        case ${ssn} in
        3)
            echo; er "  Looks like the server has a corrupted version of the file or there is a technical problem."
            echo; er2 "  Press "; eg2 "c"; er " to ignore and try again."
            eg2 "s"; er " to cancel setup..."; echo
            
            while true
            do
                read -n1 islem
                case ${islem} in
                c)
                    check="ok"; ssn="1"; break
                ;;
                s)
                    exit 1
                ;;
                esac
            done
        ;;
        *)
            check="x"; rm -rf $2; echo; er "  File is outdated or corrupted."
        esac
    ;;
    esac
}

tch() {
    f2t="${1}"
    [[ ! -e "${f2t}" ]] && touch "${f2t}"
    unset f2t
}

dlt() {
    f2d="${1}"
    [[ -e "${f2d}" ]] && rm -rf "${f2d}"
    unset f2d
}

on_off() {
    while true
    do
        [[ "$(ps a -o cmd | grep ${eg} | grep -v grep)" ]] && sleep 30s || { tch stop.eg; break; }
    done
}

net_watch() {
    until [ -e "stop.eg" ]
    do
        [[ "$(ping -nc1 www.google.com)" ]] || { [[ "$(ping -nc3 www.google.com)" ]] || connect_me &>/dev/null; }
        sleep 60s
    done
}

mirror_check() {
    until [ -e "connected.eg" ]
    do
        sleep 1s
    done
    
    [[ "$(grep 'mirror=' ${vl})" ]] && sed -i '\!^mirror=!d' ${vl}
    
    for mrr in ${mirrorlist}
    do
        # Trimming mirror name. Ex. http://gentoo.kiev.ua/ftp -->> gentoo.kiev.ua
        [[ "$(ping -nc3 $(echo ${mrr} | sed -e 's/.*\:\/\///' -e 's/\/.*$//'))" ]] && { a2v "mirror=\"${mrr}\""; break; }
    done
    
    # Cancel setup when there are no available mirrors
    [[ "$(grep 'mirror=' ${vl})" ]] || tch stop.eg
}

connect_me() {
    unset adapter trm pid
    killall ping dhcpcd ifconfig ip
    killall ping dhcpcd ifconfig ip
    killall ping dhcpcd ifconfig ip
    
    for adapter in ${adapters_found}
    do
        which ip && { ip link set ${adapter} down ; ip link set ${adapter} up; } || { ifconfig ${adapter} down; ifconfig ${adapter} up; }
        dlt "/var/run/dhcpcd-${adapter}.pid"
        sleep 3s; dhcpcd ${adapter}; sleep 7s
        [[ "$(ping -nc3 www.google.com)" ]] && { tch connected.eg; break; }
    done
}

mrg() {
    CONFIG_PROTECT_MASK="/etc" emerge $@ 2> /dev/null
}

umrg() {
    cl; eb2 "* "; eg2 "emerge "; er "--unmerge ${@}"
    for p in $@
    do
        CONFIG_PROTECT_MASK="/etc" emerge --unmerge ${p} 2> /dev/null && { sed -i "\!.*/${p}.*!d" ${compiled}; sed -i "\!.*/${p}.*!d" pkg.lst; }
    done
}

get_files() {
    lnk="$@"
    bname="$(basename $(echo ${lnk} | sed -e 's:^.*\:\/\/::' -e 's: .*::'))"
    
    while true
    do
        shut
        
        if [ -n "$(echo ${lnk} | grep -iv 'digest' | grep -iv 'md5' | grep 'tar.bz2')" ]; then
            wget --timeout=15 --tries=2 --waitretry=5 ${lnk} -O ${bname}
        else
            wget --timeout=15 --tries=2 --waitretry=5 ${lnk} -O ${bname} &>/dev/null
        fi
        
        case $? in
        0)
            break
        ;;
        *)
            mirror_check
        ;;
        esac
    done
    
    [[ -e "stop.eg" ]] && { echo; er "There are no available mirrors or setup was cancelled."; er "Exiting..."; echo; exit 1; }
}

inst() {
    make_list() {
        fl "pkg.lst" "0" "d"
        
        while read line
        do
            case "${line}" in
            "[ebuild"*)
                echo "${line}" | tr -s '[:blank:]' ' ' | sed -e 's:\[[0-9].*\]::' -e 's:\[.*ebuild.*\] :=:' -e 's: .*::' >> ${trg_file}
            ;;
            esac
        done < data.tmp
        
        while read p_line
        do
            case ${p_line} in
            =[A-Z]*/*|=[a-z]*/*)
                continue
            ;;
            *)
                sed -i "\!.*${p_line}.*!d" ${trg_file}
            ;;
            esac
        done < ${trg_file}
        
        fl "pkg_dup.lst" "0" "d"
        cp pkg.lst ${trg_file}
        
        case "${a}" in
        "-e system")
            emerge -pv --nodeps gentoo-sources | grep ebuild | grep gentoo-sources | tr -s '[:blank:]' ' ' | sed -e 's:\[[0-9].*\]::' -e 's:\[.*ebuild.*\] :=:' -e 's: .*::' >> ${trg_file}
            emerge -pv --nodeps genkernel | grep ebuild | grep genkernel | tr -s '[:blank:]' ' ' | sed -e 's:\[[0-9].*\]::' -e 's:\[.*ebuild.*\] :=:' -e 's: .*::' >> ${trg_file}
        ;;
        esac
        
        fl "fetched.lst" "0" "d"
        tch ${trg_file}
    }
    
    fetch() {
        killall "$(ps a -o pid,cmd | grep -i 'emerge -f --nodeps' | grep -v 'grep' | cut -d' ' -f1)" &>/dev/null
        while true
        do
            shut
            
            read -r pkg < pkg_dup.lst
            if [ -z "${pkg}" ]; then
                break
            else
                case "${pkg}" in
                *"/"*)
                    next="no"
                    while [ "${next}" != "yes" ]
                    do
                        CONFIG_PROTECT_MASK="/etc" emerge -f --nodeps ${pkg} 2> /dev/null
                        
                        case $? in
                        0)
                            cf "${pkg}"; next="yes"
                        ;;
                        *)
                            until [ -e "connected.eg" ]
                            do
                                sleep 1s
                            done
                        ;;
                        esac
                    done
                    sleep 1s
                ;;
                esac
            
                sed -i "\!.*${pkg}.*!d" pkg_dup.lst
            fi
        done
    }
    
    compile() {
        rcount="0"
        fl "pkg.lst" "0" "0"
        while true
        do
            read -r package < ${trg_file}
            
            if [ -z "${package}" ]; then
                break
            else
                if [ -e "${trg_file}" ]; then
                    cl
                    source "$(pwd)/merge.eg"
                    
                    [[ -n "${step}" ]] && echo "${step}"
                    
                    echo; ey2 "  Command: "; eg2 "  emerge "; er "${a}"
                    echo; eg2 "  Next packages "; ew2 "($(wc -l < ${trg_file}) packages total)"; eg ":"
                    
                    p_numb="1"
                    while read p_input
                    do
                        p_input="$(echo ${p_input} | cut -c 2-)"
                        case ${p_numb} in
                        1)
                            ey "    ${p_input}"
                        ;;
                        [2-5])
                            ew "    ${p_input}"
                        ;;
                        6)
                            break
                        ;;
                        esac
                        ((p_numb++))
                    done < ${trg_file}
                    
                    echo
                    
                    if [ -z "$(grep ${package} fetched.lst)" ]; then
                        echo; ew2 "  Waiting for package download..."
                        while [ -z "$(grep ${package} fetched.lst)" ]
                        do
                            sleep 5s
                            shut
                        done
                        ew "  Package downloaded."; echo
                    else
                        echo; echo
                    fi
                fi
                
                shut
                
                case ${package} in
                *sys-apps/kmod-*)
                    umrg "module-init-tools"
                ;;
                esac
                
                if [ -e "sys.eg" ]; then
                    mrg -e --oneshot --nodeps ${package} || mrg -e --oneshot ${package}
                else
                    if [ -n "$(grep ${package} ${compiled})" ]; then
                        mrg -u --oneshot --nodeps ${package} || mrg -u --oneshot ${package}
                    else
                        mrg --oneshot --nodeps ${package} || mrg --oneshot ${package}
                    fi
                fi
                
                case $? in
                0)
                    sed -i "\!.*${package}.*!d" ${trg_file}
                    
                    if [ -z "$(grep $(echo ${package} | cut -c 2-) ${compiled})" ]; then
                        echo "${package}" | cut -c 2- >> ${compiled}
                    fi
                    
                    [[ -e "sys.eg" ]] && refresh
                    
                    case ${package} in
                    *sys-devel/gcc-[0-9]*)
                        set_gcc && refresh
                    ;;
                    */python-[0-9]*)
                        python-updater
                    ;;
                    esac
                    rcount="0"
                ;;
                *)
                    ((rcount++))
                    rm -rf /var/tmp/portage/*$(echo ${package} | cut -c 2-)* &>/dev/null
                    
                    case ${rcount} in
                    1)
                        lff; refresh; timesync
                    ;;
                    2)
                        python-updater
                        perl-cleaner --reallyall
                    ;;
                    3)
                        tch stop.eg
                        echo; er "Installation failed due to compile error. Package: $(echo ${package} | cut -c 2-)."
                        er "Easygentoo will exit now."; echo; exit 1
                    ;;
                    esac
                ;;
                esac
            fi
        done
        
        # Making records for commands that doesn't get recorded to world file because of --oneshot parameter
        [[ "${a}" != "-e system" ]] && mrg -u ${a} 2>&1 > /dev/null
        
        step=""
    }
    
    case ${1} in
    sync)
        [[ -e "/usr/portage/metadata/timestamp.chk" ]] && rm -rf /usr/portage/metadata/timestamp.chk &>/dev/null
        CONFIG_PROTECT_MASK="/etc" emerge --quiet --sync &>/dev/null
    ;;
    *)
        fl "merge.eg" "0" "d"
        cf "a=\"${1}\""
        
        source "$(pwd)/merge.eg"
        [[ "${a}" == "-e system" ]] && echo "emerge -pvD ${a} 2>&1 | grep '^\['" > cmd.eg || echo "emerge -pv ${a} 2>&1 | grep '^\['" > cmd.eg
        sh cmd.eg > data.tmp; rm -rf cmd.eg
        
        if [ -n "$(grep -i '^\[ebuild' data.tmp)" ]; then
            make_list
            fetch &>/dev/null &
            compile
        fi
    ;;
    esac
}

k_grub() {
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "grub "; eg "..."; echo; sleep 0.5s)
    inst "grub"
    
    echo; eg2 "  Creating "; er2 "grub.conf"; eg "..."; sleep 0.5s

    krnl="$(ls /boot/kernel-${eg}*)"
    [[ -e "${krnl}" ]] && krnl2="$(ls /boot/kernel-${eg}* | cut -c 6-)" || krnl2="/kernel-not-available"

    init="$(ls /boot/initramfs-${eg}*)"
    [[ -e "${init}" ]] && init2="$(ls /boot/initramfs-${eg}* | cut -c 6-)" || init2="/initramfs-not-available"
    
    [[ -n "${boot_part}" ]] && { bn="$(echo ${boot_part} | cut -c 4-)"; bn="$((bn-1))"; }

    rn="$(echo ${root_part} | cut -c 4-)"; rn="$((rn-1))"

    case $(echo ${grub} | cut -c 3-) in
    [a-z])
        dn="$(echo ${grub} | cut -c 3- | tr 'a-z' '0-26')"
    ;;
    [a-z][0-9])
        dn="$(echo ${grub} | cut -c 3- | cut -c -1 | tr 'a-z' '0-26')"
    ;;
    [a-z][0-9][0-9])
        dn="$(echo ${grub} | cut -c 3- | cut -c -2 | tr 'a-z' '0-26')"
    ;;
    esac
    
    if [ -n "${boot_part}" ]; then
        pn="${bn}"
        splash="splashimage=(hd${dn},${pn})/grub/splash.xpm.gz"
        kernel_line="kernel (hd${dn},${pn})${krnl2}"
        init_line="initrd (hd${dn},${pn})${init2}"
    else
        pn="${rn}"
        splash="splashimage=(hd${dn},${pn})/boot/grub/splash.xpm.gz"
        kernel_line="kernel ${krnl}"
        init_line="initrd ${init}"
    fi
    
    [[ -n "${swap_part}" ]] && kernel_line="${kernel_line} real_resume=LABEL=${swap_label}"
    kernel_line="${kernel_line} real_root=LABEL=${root_label} udev"
    
    case ${root_fs} in
    jfs)
        [[ -z "${boot_part}" ]] && kernel_line="${kernel_line} ro"
    ;;
    esac
    
    fl "grub.eg" "0" "d"
    
    cf '#This file is created automatically.'
    cf ' '
    cf 'default 0'
    cf 'timeout 10'
    cf "${splash}"
    cf ' '
    cf "title Gentoo Linux"
    cf "root (hd${dn},${pn})"
    cf "${kernel_line}"
    cf "${init_line}"
    cf ' '
    
    if [ -n "${windows}" ]; then
        case $(echo ${windows} | cut -c 3-) in
        [a-z][0-9])
            wdn=$(echo ${windows} | cut -c 3- | cut -c -1 | tr 'a-z' '0-26')
        ;;
        [a-z][0-9][0-9])
            wdn=$(echo ${windows} | cut -c 3- | cut -c -2 | tr 'a-z' '0-26')
        ;;
        esac
        
        wpn="$(echo ${windows} | cut -c 4-)"
        wpn=$((wpn-1))
    
        cf "title Windows"
        cf "rootnoverify (hd${wdn},${wpn})"
        cf "makeactive"
        cf "chainloader +1"
        cf " "
    fi
    
    [[ -e "/boot/grub/grub.conf" ]] && { cp /boot/grub/grub.conf /boot/grub/grub.conf.backup; rm -rf /boot/grub/grub.conf; }

    cp grub.eg /boot/grub/grub.conf

    echo; eg2 "  Installing grub to "; er2 "${grub}"; eg "..."; echo; sleep 0.5s
    
    [[ -n "${boot_part}" ]] && cp /proc/mounts /etc/mtab || grep -v rootfs /proc/mounts > /etc/mtab

    [[ -e "/boot/grub/device.map" ]] && sed -i "\!.*fd[0-9].*!d" /boot/grub/device.map
    
    fl "ginst.eg" "0" "d"
    
    cf "root (hd${dn},${pn})"
    cf "setup (hd${dn})"
    cf "quit"
    
    grub < ${trg_file}
}

k_kernel() {
    step=$(echo; eb2 "* "; eg "Emerging kernel... "; echo; sleep 0.5s)
    inst "genkernel gentoo-sources"
    step=$(echo; eb2 "* "; eg "Emerging filesystem tools... "; echo; sleep 0.5s)
    inst "${progs}"
    
    echo; eg2 "  Creating kernel config"; eg "..."; echo; sleep 0.5s
    
    get_files "https://raw.github.com/shdcn/easygentoo/master/easygentoo.config"
    
    fl "easygentoo.config" "0" "0"
    
    case ${arch} in
    i686)
        avoid_dup_kernel "CONFIG_64BIT=n"
    ;;
    amd64)
        avoid_dup_kernel "CONFIG_64BIT=y"
    ;;
    esac
    
    [[ ! -d "/etc/kernels" ]] && mkdir -p /etc/kernels

    cp easygentoo.config /etc/kernels
    
    echo; eb2 "* "; eg2 "Compiling kernel... "; er "(genkernel)"; echo; sleep 0.5s
    genkernel --bootdir=/boot --bootloader=grub --disklabel --install --kernel-config=/etc/kernels/easygentoo.config --kernname=${eg} --makeopts=-j${core} --no-mountboot --postclear --save-config all
    
    [[ $(ls /boot/kernel-${eg}-*) ]] || genkernel --bootdir=/boot --bootloader=grub --disklabel --install --kernel-config=/etc/kernels/easygentoo.config --kernname=${eg} --makeopts=-j${core} --no-mountboot --postclear --save-config all
}

k_must() {
    cl
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "dhcpcd"; eg2 " and "; er2 "gentoolkit"; eg "... "; echo; sleep 0.5s)
    inst "dhcpcd gentoolkit";

    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "lafilefixer"; eg "... "; echo; sleep 0.5s)
    inst "lafilefixer"
}

k_needed() {
    step=$(echo; eb2 "* "; eg "Emerging basic tools..."; echo; sleep 0.5s)
    inst "acpid bash-completion consolekit dbus localepurge net-misc/ntp sudo"
    
    timesync
    eselect bashcomp enable --global gentoo

    echo; eb2 "* "; eg2 "Starting services... "; er "(dbus consolekit udev)"; echo; sleep 0.5s
    
    for srv in "dbus consolekit udev"
    do
        /etc/init.d/${srv} stop &>/dev/null
        /etc/init.d/${srv} start &>/dev/null
    done
    
    echo; eb2 "* "; eg "Adjusting basic tools to start at boot..."; sleep 0.5s

    for adapter in ${adapters_found}
    do
        net="net.${adapter}"

        [[ ! -e "/etc/init.d/${net}" ]] && ln -s /etc/init.d/net.lo /etc/init.d/${net}

        case ${setup} in
        basic)
            rc-update add ${net} default &>/dev/null
        ;;
        esac
    done
    
    rc-update add acpid default &>/dev/null
    rc-update add consolekit default &>/dev/null
    rc-update add dbus default &>/dev/null
    rc-update add udev sysinit &>/dev/null
    rc-update add udev-mount default &>/dev/null
    rc-update add udev-postmount default &>/dev/null
    
    case ${type} in
    pc)
        rc-update add numlock default &>/dev/null
    ;;
    esac
}

k_portage() {
    step=$(echo; eb2 "* "; eg2 "Updating "; er2 "portage"; eg "... "; sleep 0.5s)
    rm -rf /etc/make.profile

    case ${setup} in
    basic)
        case ${kw} in
        amd64)
            eselect profile set default/linux/amd64/13.0
        ;;
        x86)
            eselect profile set default/linux/x86/13.0
        ;;
        esac
    ;;
    normal)
        case ${kw} in
        amd64)
            eselect profile set default/linux/amd64/13.0/desktop
        ;;
        x86)
            eselect profile set default/linux/x86/13.0/desktop
        ;;
        esac
    ;;
    esac
    
    eb2 "* "; eg "emerge --sync (this may take a while)"
    inst "sync"
    inst "--nodeps portage"
}

k_nm() {
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "NetworkManager"; eg "..."; sleep 0.5s; echo)
    inst "networkmanager nm-applet"

    rc-update add NetworkManager default &>/dev/null
    
    fl "/usr/share/polkit-1/actions/org.freedesktop.NetworkManager.policy" "b" "0"
    sed -i s/"<allow_active>.*<\/allow_active>"/"<allow_active>yes<\/allow_active>"/ ${trg_file}
}

k_alsa() {
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "Alsa"; eg "..."; echo)
    inst "alsa-utils"
    rc-update add alsasound boot
    
    sound_card_guess="$(aplay -l | grep card | awk '{print $3}' | grep -iv dummy | grep -iv pcsp | uniq | sed q)"
    
    if [ -n "${sound_card_guess}" ]; then
        echo "pcm.!default { type hw card ${sound_card_guess} }" > /etc/asound.conf
        echo "ctl.!default { type hw card ${sound_card_guess} }" >> /etc/asound.conf
    fi
    
    fl "/etc/conf.d/alsasound" "0" "0"
    avoid_dup 'RESTORE_ON_START="yes"'
    avoid_dup 'SAVE_ON_STOP="yes"'
    avoid_dup 'LOAD_ON_START="yes"'
    
    amixer set Master unmute
    amixer set PCM unmute
    
    alsactl -f /var/lib/alsa/asound.state store
}

k_x() {
    step=$(echo; eb2 "* "; eg2 "Checking system"; eg "..."; echo)
    inst "-N system"
    
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "Xorg server"; eg "..."; echo)
    inst "xorg-server"
    
    step=$(echo; eb2 "* "; eg2 "Emerging necessary tools"; sleep 0.5s; echo)
    inst "dejavu eselect-fontconfig fontconfig mesa-progs setxkbmap"
    
    fl "/home/${username}/.xinitrc" "b" "0"

    case ${keymap} in
    br)
        cf "setxkbmap -model evdev -layout br"
    ;;
    trq)
        cf "setxkbmap -model evdev -layout tr"
    ;;
    trf)
        cf "setxkbmap -model evdev -layout tr -variant f"
    ;;
    us)
        cf "setxkbmap -model evdev -layout us"
    ;;
    esac
    
    cf "export GDK_USE_XFT=1"
    cf "export QT_XFT=true"
    cf ""
    cf "#This line is necessary if you don't use a login manager to start Xfce"
    cf "#exec $(which ck-launch-session) $(which dbus-launch) --exit-with-session xfce4-session"
    
    k_xfce
    
    fl "/home/${username}/.gtkrc-2.0" "b" "d"
    
    cf "include \"/usr/share/themes/MurrinaBlu/gtk-2.0/gtkrc\""
    cf ''
    cf 'style "user-font" {'
    cf '    font_name = "DejaVu Sans 9"'
    cf '}'
    cf ''
    cf 'style "xfdesktop-icon-view" {'
    cf '    XfdesktopIconView::label-alpha = 10'
    cf '    base[NORMAL] = "#000000"'
    cf '    base[SELECTED] = "#71B9FF"'
    cf '    base[ACTIVE] = "#71FFAD"'
    cf '    fg[NORMAL] = "#ffffff"'
    cf '    fg[SELECTED] = "#71B9FF"'
    cf '    fg[ACTIVE] = "#71FFAD"'
    cf '}'
    cf ''
    cf 'widget_class "*XfdesktopIconView*" style "xfdesktop-icon-view"'
    cf ''
    cf 'widget_class "*" style "user-font"'
    cf 'gtk-font-name = "DejaVu Sans 9"'
    cf 'gtk-theme-name = "MurrinaBlu"'
    
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "Gdm"; eg " login manager..."; echo)
    k_gdm
    
    active=$(eselect opengl list | grep "xorg-x11" | grep "*")

    if [ -z "${active}" ]; then
        eselect opengl set xorg-x11
    fi

    hwsetup
    refresh
    
    echo; eb2 "* "; eg2 "Making adjustments for "; er "evdev "; echo
    
    fl "/etc/X11/xorg.conf.d/05-evdev.conf" "b" "d"

    cf 'Section "InputClass"'
    cf '    Identifier "mouse-all"'
    cf '    MatchIsPointer "on"'
    cf '    MatchDevicePath "/dev/input/event*"'
    cf '    Driver "evdev"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '    Identifier "keyboard-all"'
    cf '    MatchIsKeyboard "on"'
    cf '    MatchDevicePath "/dev/input/event*"'
    cf '    Driver "evdev"'
        case ${keymap} in
        br)
            cf '    Option "XkbLayout" "br"'
        ;;
        trq|trf)
            cf '    Option "XkbLayout" "tr"'
            case ${keymap} in
            trf)
                cf '    Option "XkbVariant" "f"'
            ;;
            esac
        ;;
        us)
            cf '    Option "XkbLayout" "us"'
        ;;
        esac
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '    Identifier "touchpad-all"'
    cf '    MatchIsTouchpad "on"'
    cf '    MatchDevicePath "/dev/input/event*"'
    cf '    Driver "evdev"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '    Identifier "tablet-all"'
    cf '    MatchIsTablet "on"'
    cf '    MatchDevicePath "/dev/input/event*"'
    cf '    Driver "evdev"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '    Identifier "touchscreen-all"'
    cf '    MatchIsTouchscreen "on"'
    cf '    MatchDevicePath "/dev/input/event*"'
    cf '    Driver "evdev"'
    cf 'EndSection'

    fl "/etc/X11/xorg.conf.d/10-synaptics.conf" "b" "d"

    cf 'Section "InputClass"'
    cf '  Identifier "touchpad catchall"'
    cf '  MatchIsTouchpad "on"'
    cf '  MatchDevicePath "/dev/input/event*"'
    cf '  Driver "synaptics"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '  Identifier "Dell Inspiron embedded buttons quirks"'
    cf '  MatchTag "inspiron_1011|inspiron_1012"'
    cf '  MatchDevicePath "/dev/input/event*"'
    cf '  Driver "synaptics"'
    cf '  Option "JumpyCursorThreshold" "90"'
    cf '  Option "AreaBottomEdge" "4100"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '  Identifier "Dell Inspiron quirks"'
    cf '  MatchTag "inspiron_1120"'
    cf '  MatchDevicePath "/dev/input/event*"'
    cf '  Driver "synaptics"'
    cf '  Option "JumpyCursorThreshold" "250"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '  Identifier "HP Mininote quirks"'
    cf '  MatchTag "mininote_1000"'
    cf '  MatchDevicePath "/dev/input/event*"'
    cf '  Driver "synaptics"'
    cf '  Option "JumpyCursorThreshold" "20"'
    cf 'EndSection'

    fl "/etc/X11/xorg.conf.d/10-vmmouse.conf" "b" "d"

    cf 'Section "InputClass"'
    cf '  Identifier "vmmouse catchall"'
    cf '  MatchTag "vmmouse"'
    cf '  MatchDevicePath "/dev/input/event*"'
    cf '  Driver "vmmouse"'
    cf 'EndSection'

    fl "/etc/X11/xorg.conf.d/10-wacom.conf" "b" "d"

    cf 'Section "InputClass"'
    cf '  Identifier "Wacom Class"'
    cf '  MatchProduct "Wacom|WACOM"'
    cf '  MatchDevicePath "/dev/input/event*"'
    cf '  Driver "wacom"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '  Identifier "Wacom serial class"'
    cf '  MatchProduct "Serial Wacom Tablet"'
    cf '  Driver "wacom"'
    cf '  Option "ForceDevice" "ISDV4"'
    cf 'EndSection'
    cf ''
    cf 'Section "InputClass"'
    cf '  Identifier "Wacom serial class identifiers"'
    cf '  MatchProduct "WACf|FUJ02e5|FUJ02e7"'
    cf '  Driver "wacom"'
    cf 'EndSection'
    cf ''
    cf '# N-Trig Duosense Electromagnetic Digitizer'
    cf 'Section "InputClass"'
    cf '  Identifier "Wacom N-Trig class"'
    cf '  MatchProduct "HID 1b96:0001|N-Trig Pen"'
    cf '  MatchDevicePath "/dev/input/event*"'
    cf '  Driver "wacom"'
    cf '  Option "Button2" "3"'
    cf 'EndSection'
    
    fl "/etc/X11/xorg.conf.d/20-magictrackpad.conf" "b" "d"
    
    cf 'Section "InputClass"'
    cf '  Identifier "Magic Trackpad"'
    cf '  MatchUSBID "05ac:030e"'
    cf '  Driver "evdev"'
    cf 'EndSection'

    fl "xorg.eg" "0" "0"
    
    cf 'Section "Files"'
    
    ls /usr/share/fonts >> fonts.eg
    
    while read fontdir
    do
        case ${fontdir} in
        75dpi|100dpi|misc)
            cf '  FontPath "/usr/share/fonts/'${fontdir}':unscaled"'
        ;;
        *)
            cf '  FontPath "/usr/share/fonts/'${fontdir}'"'
        ;;
        esac
    done < fonts.eg
    
    cf 'EndSection'
    cf ''
    cf 'Section "ServerFlags"'
    cf '    Option  "DontZap" "off"'
    cf 'EndSection'
    cf ''
    cf 'Section "Device"'
    cf '    Identifier "video-card"'
    cf '    Driver  "vesa"'
    cf '    Option  "Monitor-default" "monitor"'
    cf 'EndSection'
    cf ''
    cf 'Section "Monitor"'
    cf '    Identifier  "monitor"'
    cf '    VertRefresh  50-70'
    cf '    HorizSync  30-80'
    cf '    Option  "Enable" "true"'
    cf '    Option  "TargetRefresh" "60"'
    cf '    Option  "RenderAccel" "True"'
        case ${type} in
        laptop)
            cf '    Option  "DPMS" "true"'
        ;;
        esac
    cf 'EndSection'
    cf ''
    cf 'Section "Screen"'
    cf '    Identifier  "general"'
    cf '    Device   "video-card"'
    cf '    Monitor  "monitor"'
    cf 'EndSection'
    cf ''
    cf 'Section "ServerLayout"'
    cf '    Identifier  "general-layout"'
    cf '    Screen  "general"'
    cf '    Option  "BackingStore" "True"'
    cf 'EndSection'
    cf ''
    cf 'Section "Module"'
    cf '    Load  "dbe"'
    cf '    Load  "dri"'
    cf '    Load  "dri2"'
    cf '    Load  "evdev"'
    cf '    Load  "extmod"'
    cf '    SubSection  "extmod"'
    cf '      Option    "omit xfree86-dga"'
    cf '    EndSubSection'
    cf '    Load  "freetype"'
    cf '    Load  "glx"'
    cf 'EndSection'
    cf ''
    cf 'Section "Extensions"'
    cf '    Option  "Composite"  "Enable"'
    cf 'EndSection'
    
    fl "/etc/X11/xorg.conf" "b" "d"
    
    cp xorg.eg ${trg_file}
    
    fl "/home/${username}/.fonts.conf" "b" "d"

    cf '<?xml version="1.0" encoding="UTF-8"?>'
    cf '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">'
    cf '<fontconfig>'
    cf '    <alias>'
    cf '        <family>serif</family>'
    cf '        <prefer>'
    cf '            <family>DejaVu Serif</family>'
    cf '            <family>Bitstream Vera Serif</family>'
    cf '        </prefer>'
    cf '    </alias>'
    cf ''
    cf '    <alias>'
    cf '        <family>sans-serif</family>'
    cf '        <prefer>'
    cf '            <family>DejaVu Sans</family>'
    cf '            <family>Bitstream Vera Sans</family>'
    cf '            <family>Verdana</family>'
    cf '            <family>Arial</family>'
    cf '        </prefer>'
    cf '    </alias>'
    cf ''
    cf '    <alias>'
    cf '        <family>monospace</family>'
    cf '        <prefer>'
    cf '            <family>DejaVu Sans Mono</family>'
    cf '            <family>Bitstream Vera Sans Mono</family>'
    cf '        </prefer>'
    cf '    </alias>'
    cf ''
    cf '    <match target="font">'
    cf '        <edit name="rgba" mode="assign">'
    cf '            <const>none</const>'
    cf '        </edit>'
    cf '        <edit name="autohint" mode="assign">'
    cf '            <bool>true</bool>'
    cf '        </edit>'
    cf '        <edit name="antialias" mode="assign">'
    cf '            <bool>true</bool>'
    cf '        </edit>'
    cf '        <edit name="hinting" mode="assign">'
    cf '            <bool>true</bool>'
    cf '        </edit>'
    cf '        <edit name="hintstyle" mode="assign">'
    cf '            <const>hintfull</const>'
    cf '        </edit>'
    cf '    </match>'
    cf ''
    cf '    <!-- Disable autohint for bold fonts -->'
    cf '    <match target="font">'
    cf '           <test name="weight" compare="more">'
    cf '            <const>medium</const>'
    cf '        </test>'
    cf '           <edit name="autohint" mode="assign">'
    cf '            <bool>false</bool>'
    cf '        </edit>'
    cf '    </match>'
    cf ''
    cf '    <!-- Reject bitmap fonts in favour of Truetype, Postscript, etc. -->'
    cf '    <selectfont>'
    cf '        <rejectfont>'
    cf '            <pattern>'
    cf '                <patelt name="scalable">'
    cf '                    <bool>false</bool>'
    cf '                </patelt>'
    cf '            </pattern>'
    cf '        </rejectfont>'
    cf '    </selectfont>'
    cf ''
    cf '</fontconfig>'

    for cfg in "10-autohint.conf" "10-sub-pixel-rgb.conf" "20-unhint-small-dejavu-sans-mono.conf" "20-unhint-small-dejavu-sans.conf" "20-unhint-small-dejavu-serif.conf" "25-unhint-nonlatin.conf" "57-dejavu-sans-mono.conf" "57-dejavu-sans.conf" "57-dejavu-serif.conf"
    do
        no=$(eselect fontconfig list | grep "${cfg}" | tr '[]' ' ' | awk '{print $1}')
        eselect fontconfig enable "${no}" &>/dev/null
    done
}

k_gdm() {
    inst "gdm gdm-themes"
    
    h=$(grep gdm /etc/group | cut -d: -f1)
    if [ "${h}" != "gdm" ]; then
        groupadd gdm
    fi

    if [ -z "$(grep gdm /etc/passwd | cut -d: -f1)" ]; then
        useradd gdm -s /sbin/nologin -g gdm
    fi
    
    session_name="$(ls /usr/share/xsessions/ | grep -iv fluxbox | grep -iv gnome | grep -iv kde | grep -iv lxde | grep -iv openbox | grep -i xfce)"
    
    fl "/etc/X11/gdm/custom.conf" "b" "d"
    
    cf "[daemon]"
    cf "DefaultSession=${session_name}"
    cf "[greeter]"
    cf "GraphicalTheme=soft-flower-gdm"
    cf "Use24Clock=true"
    
    chown -fP ${username} ${trg_file}
    
    session_name2="$(echo ${session_name} | cut -d'.' -f1)"
    
    fl "/home/${username}/.dmrc" "0" "d"
    
    cf "[Desktop]"
    cf "Session=${session_name2}"
    
    chown -fP ${username} ${trg_file}
    
    rc-update add xdm default &>/dev/null

    fl "/etc/conf.d/xdm" "0" "0"
    
    avoid_dup 'DISPLAYMANAGER="gdm"'
    avoid_dup 'NEEDS_HALD="no"'
    
    chown -fP ${username} ${trg_file}
}

k_xfce() {
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "Xfce"; eg " desktop environment..."; sleep 0.5s; echo)
    inst "xfce4-meta xfce4-notifyd"
    step=$(echo; eb2 "* "; eg "Emerging other Xfce packages..."; sleep 0.5s; echo)
    inst "app-editors/leafpad x11-terms/xfce4-terminal x11-themes/murrine-themes xarchiver xfce4-mixer xfce4-taskmanager"
    
    case "${type}" in
    laptop)
        step=$(echo; eb2 "* "; eg "Emerging packages needed for laptops..."; sleep 0.5s; echo)
        inst "xfce4-battery-plugin xfce4-power-manager laptop-mode-tools"
        rc-update add laptop_mode default &>/dev/null
    ;;
    esac
    
    step=$(echo; eb2 "* "; eg2 "Emerging "; er2 "Thunar"; eg "..."; sleep 0.5s; echo)
    inst "thunar thunar-archive-plugin thunar-volman trayer"
    
    if [ ! -d "/home/${username}/.config/xfce4/panel" ]; then
        mkdir -p /home/${username}/.config/xfce4/panel
    fi
    
    cp /etc/xdg/xfce4/panel/default.xml /home/${username}/.config/xfce4/panel/
    
    usermod -a -G plugdev ${username}
    
    session="Xfce4"
    
    fl "/etc/env.d/90xsession" "0" "d"
    
    avoid_dup 'XSESSION="'${session}'"'
}

k_system() {
    touch sys.eg
    step=$(echo; eb2 "* "; eg "Updating system..."; echo; sleep 0.5s)
    inst "-e system"
    rm -rf sys.eg
}

k_check() {
    step=$(echo; eb2 "* "; eg "Checking system..."; echo; sleep 0.5s)
    inst "-uDN world"
    rdr
}

set_gcc() {
    gcc-config -l | awk '{print $2}' > gcc.lst
    gcc_latest="$(sort -r gcc.lst | sed q)"
    gcc-config ${gcc_latest} &>/dev/null || gcc-config ${gcc_latest} &>/dev/null
    rm -rf gcc.lst
}

timesync() {
    which ntpdate &>/dev/null && { echo; eb2 "* "; eg "ntpdate -b -u pool.ntp.org"; echo; ntpdate -b -u pool.ntp.org; } || { which sntp &>/dev/null && sntp -t10 pool.ntp.org &>/dev/null; }
}

refresh() {
    echo "-5" | CONFIG_PROTECT_MASK="/etc" etc-update &>/dev/null; env-update &>/dev/null; source /etc/profile &>/dev/null
    vlist
    echo
}

lff() {
    which lafilefixer &>/dev/null && { echo; eb2 "* "; eg "lafilefixer --justfixit"; echo; lafilefixer --justfixit; }
}

rdr() {
    which revdep-rebuild &>/dev/null && { echo; eb2 "* "; eg "revdep-rebuild"; echo; revdep-rebuild; }
}

vlist() {
    source "$(pwd)/${vl}"
}

start() {
    export SHELL=$(which bash); setterm -blank 0; cl
    
    eg="easygentoo"; profile="profile"; vl="variables"; mnt="/mnt/gentoo"
    lt="latest-stage3.txt"; compiled="compiled.txt"
    
    [[ -e "/chroot.eg" ]] && inside || { intro; check; prepare; get_tar; move; }

    exit 0
}

intro() {
    cl; echo; echo
    echo; eg "  Welcome to Easy Gentoo!"; echo; sleep 0.5s
    echo; ey "  Please make sure that your profile is configured the way you exactly need it."
    ey "  The setup is automated and not even a single key press is needed till the end (if everything goes as planned ^^).";
    sleep 0.5s; echo; ew2 "  Press any key to continue..."; echo; read -n1 key; echo
    cl; eg "  Good luck ;)"; sleep 1s
}

check() {
    rm -rf easygentoo.config *.DIGESTS *.eg *.md5sum *.tmp *.lst ${lt} ${vl}
    
    [[ "$(pwd)" != "/root" ]] && { echo; er2 "Please move the script to "; ey2 "/root"; er " and start it again."; exit 1; }
    
    [[ ! -e "${profile}" ]] && { cl; er "  Looks like you don't have a profile. Please create one."; echo; exit 1; }
    
    [[ ! -d "${mnt}" ]] && mkdir -p ${mnt}
    
    for var in "arch blimit domainname grub hostname keymap setup rootpass userpass username windows"
    do
        unset ${var}
    done
    
    for var2 in "boot swap root home extra"
    do
        unset ${var2}_part ${var2}_label ${var2}_fs ${var2}_mp
    done
    
    for var3 in "fse fs_exist progs adapters_found core kw tarball type available_cpu_flags"
    do
        unset ${var3}
    done
    
    echo "$(tr -s '[:blank:]' ' ' < ${profile})" > ${profile}
    
    necessary="awk bash cat chmod chroot clear cp cut fdisk free grep ip loadkeys md5sum mkdir mount mv rm sed setterm sha512sum sleep swapoff swapon tar touch tr umount wc wget"
    nicknames="boot extra home root swap"
    
    a2v "fs_list=\"btrfs ext2 ext3 ext4 ntfs reiserfs xfs\""
    
    for nick in ${nicknames}
    do
        for a in ${fs_list}
        do
            t=$(grep "${nick} " "${profile}" | grep "${a}")
            if [ -n "${t}" ]; then
                added1=$(echo "${fse}" | grep "${a}")
                if [ -z "${added1}" ]; then
                    [[ -z "${fse}" ]] && fse="${a}" || fse="${a} ${fse}"
                fi

                added2=$(echo "${necessary}" | grep "mkfs.${a}")
                [[ -z "${added2}" ]] && necessary="mkfs.${a} ${necessary}"
            fi
        done
    done
    
    a2v "fs_exist=\"${fse}\""

    echo; eb2 "* "; eg "Checking the existence of necessary tools..."; echo; sleep 1s
    
    for b in ${necessary}
    do
        exist "${b}"
    done
    
    sleep 1s
    
    progs="ntfs3g pcmciautils procps"

    for g in ${fs_list}
    do
        pr_need=$(echo "${fs_exist}" | grep "${g}")

        if [ -n "${pr_need}" ]; then
            case ${g} in
            btrfs)
                fsprogs="btrfs-progs"
            ;;
            ext2|ext3|ext4)
                fsprogs="e2fsprogs e2fsprogs-libs"
            ;;
            nfs)
                fsprogs="nfs-utils"
            ;;
            reiserfs)
                fsprogs="libaal reiserfsprogs"
            ;;
            xfs)
                fsprogs="xfsprogs"
            ;;
            esac

            added3=$(echo "${progs}" | grep "${fsprogs}")
            [[ -z "${added3}" ]] && progs="${fsprogs} ${progs}"
        fi
    done
    
    a2v "progs=\"${progs}\""

    unset adapter
    for adapter in eth0 eth1 eth2 eth3 eth4 eth5
    do
        ip -s link show "${adapter}" &>/dev/null && echo "${adapter}" >> adapters.eg
    done
    
    [[ -e adapters.eg ]] && adapters_found="$(cat adapters.eg | tr '\n' ' ' | sed 's/ *$//')"
    [[ -z "${adapters_found}" ]] && { echo; er "Looks like there aren't any network adapters. Setup is unable to continue. Exiting now..." ; echo; echo; exit 1; }

    a2v "adapters_found=\"${adapters_found}\""
    
    fdisk -l 2>/dev/null | awk '/^\/dev\/[s:h]d/ {print $1}' > partition_list.tmp
}

prepare() {
    file_format() {
        case ${fs} in
        swap)
            prm="sw,noatime,loop"
            echo "swapoff /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkswap -L ${label} /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        btrfs)
            prm="defaults,noatime,autodefrag,noacl,compress-force=lzo"
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkfs.${fs} -L ${label} -s 1024 /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        ext2)
            prm="defaults,noatime"
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkfs.${fs} -L ${label} -b 1024 /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        ext3)
            prm="defaults,noatime"
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkfs.${fs} -L ${label} -b 1024 /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "tune2fs -c 0 -i 1m -I 256 -O dir_index,has_journal -o journal_data_ordered -m 1 /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "e2fsck -fpDC0 /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        ext4)
            prm="defaults,noatime"
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkfs.${fs} -L ${label} -b 1024 /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "tune2fs -c 0 -i 1m -O dir_index,has_journal -o journal_data_ordered -m 1 /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "e2fsck -fpDC0 /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        ntfs)
            case ${keymap} in
            br)
                prm="defaults,locale=pt_BR.utf8,users,nls=utf8,umask=000"
            ;;
            trq|trf)
                prm="defaults,locale=tr_TR.utf8,users,nls=utf8,umask=000"
            ;;
            us)
                prm="defaults,locale=en_US.utf8,users,nls=utf8,umask=000"
            ;;
            esac
            
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkfs.${fs} -Q -L ${label} --no-indexing -f /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        reiserfs)
            prm="defaults,noatime"
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkfs.${fs} -q -l ${label} /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        xfs)
            prm="defaults,noatime,logbufs=8,logbsize=32k,osyncisdsync"
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> format.eg
            echo "mkfs.${fs} -L ${label} -f -l internal,lazy-count=1,size=64m -d agcount=2 -n size=8k -i size=1024 /dev/${part} > /dev/null 2>&1 || 
            mkfs.${fs} -L ${label} -f -l internal,lazy-count=1,size=32m -d agcount=2 -n size=8k -i size=1024 /dev/${part} > /dev/null 2>&1 || 
            mkfs.${fs} -L ${label} -f -l internal,lazy-count=1 -n size=8k -i size=1024 /dev/${part} > /dev/null 2>&1" >> format.eg
        ;;
        esac
        
        echo " " >> format.eg
    }

    file_fstab() {
        case "${fs}" in
        ntfs)
            echo "LABEL=${label}   ${mp}   ntfs-3g   ${prm}   ${dp}"  >> fstab.eg
        ;;
        *)
            echo "LABEL=${label}   ${mp}   ${fs}   ${prm}   ${dp}"  >> fstab.eg
        ;;
        esac
    }

    file_mount() {
        case ${fs} in
        swap)
            echo "swapoff /dev/${part} > /dev/null 2>&1" >> mount.eg
            echo "swapon /dev/${part} > /dev/null 2>&1" >> mount.eg
        ;;
        root)
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> mount.eg
            echo "mount -t ${fs} /dev/${part} ${mnt}${mp} -o ${prm} || mount /dev/${part} ${mnt}${mp} > /dev/null 2>&1" >> mount.eg
        ;;
        *)
            echo "umount -l /dev/${part} > /dev/null 2>&1" >> mount.eg
            
            [[ ! -d "${mnt}${mp}" ]] && echo "mkdir -p ${mnt}${mp}" >> mount.eg
            
            echo "mount -t ${fs} /dev/${part} ${mnt}${mp} -o ${prm} > /dev/null 2>&1 || mount /dev/${part} ${mnt}${mp} > /dev/null 2>&1" >> mount.eg
        ;;
        esac
    }

    default_value() {
        case ${1} in
        arch)
            value="$(uname -m)"
            
            case ${value} in
            x86_64)
                value="amd64"
            ;;
            esac
        ;;
        blimit)
            value="0"
        ;;
        domainname)
            value="easygentoo"
        ;;
        grub)
            value="$(echo ${root_part} | sed s:[0-9].*::)"
        ;;
        hostname)
            value="freshinstall"
        ;;
        keymap)
            value="us"
        ;;
        username)
            value="owner"
        ;;
        userpass)
            value="resu"
        ;;
        root)
            echo; er "  /root partition is not specified in profile. Please change your profile and start again."; echo; exit 1
        ;;
        rootpass)
            value="toor"
        ;;
        setup)
            value="basic"
        ;;
        type)
            value="pc"
        ;;
        windows)
            value=""
        ;;
        esac
    }
    
    rm -rf mount.eg
    echo "normal=$'\e[0m'" >> mount.eg
    echo "red=$'\e[31;01m'" >> mount.eg
    echo "blue=$'\e[34;01m'" >> mount.eg

    rm -rf format.eg
    echo "normal=$'\e[0m'" >> format.eg
    echo "red=$'\e[31;01m'" >> format.eg
    echo "blue=$'\e[34;01m'" >> format.eg
    
    if [ -n "$(grep '^root ' ${profile})" ]; then
        grep '^root ' ${profile} > p.tmp
        part="$(awk '{print $2}' p.tmp)"; label="$(awk '{print $3}' p.tmp)"
        fs="$(awk '{print $4}' p.tmp)"; mp="/"; dp="0 1"
        a2v "root_part=\"${part}\"   root_label=\"${label}\"   root_fs=\"${fs}\"   root_mp=\"${mp}\""
        
        echo 'echo -n ${red} "      * "; echo ${blue}"formatting root partition..."${normal}; sleep 0.5s' >> format.eg
        file_format; file_fstab
        echo 'echo -n ${red} "      * "; echo ${blue}"mounting root partition..."${normal}; sleep 0.5s' >> mount.eg
        file_mount
    fi

    if [ -n "$(grep '^boot ' ${profile})" ]; then
        grep '^boot ' ${profile} > p.tmp
        part="$(awk '{print $2}' p.tmp)"; label="$(awk '{print $3}' p.tmp)"
        fs="ext2"; mp="/boot"; dp="1 2"
        a2v "boot_part=\"${part}\"   boot_label=\"${label}\"   boot_fs=\"${fs}\"   boot_mp=\"${mp}\""
        
        echo 'echo -n ${red} "      * "; echo ${blue}"formatting boot partition..."${normal}; sleep 0.5s' >> format.eg
        file_format; file_fstab
        echo 'echo -n ${red} "      * "; echo ${blue}"mounting boot partition..."${normal}; sleep 0.5s' >> mount.eg
        file_mount
    fi

    if [ -n "$(grep '^swap ' ${profile})" ]; then
        grep '^swap ' ${profile} > p.tmp
        part="$(awk '{print $2}' p.tmp)"; label="$(awk '{print $3}' p.tmp)"
        fs="swap"; mp="none"; dp="0 0"
        a2v "swap_part=\"${part}\"   swap_label=\"${label}\"   swap_fs=\"${fs}\"   swap_mp=\"${mp}\""
        
        echo 'echo -n ${red} "      * "; echo ${blue}"formatting swap partition..."${normal}; sleep 0.5s' >> format.eg
        file_format; file_fstab
        echo 'echo -n ${red} "      * "; echo ${blue}"activating swap partition..."${normal}; sleep 0.5s' >> mount.eg
        file_mount
    fi

    if [ -n "$(grep '^home ' ${profile})" ]; then
        grep '^home ' ${profile} > p.tmp
        part="$(awk '{print $2}' p.tmp)"; label="$(awk '{print $3}' p.tmp)"
        fs="$(awk '{print $4}' p.tmp)"; mp="/home"; dp="0 0"
        a2v "home_part=\"${part}\"   home_label=\"${label}\"   home_fs=\"${fs}\"   home_mp=\"${mp}\""
        
        echo 'echo -n ${red} "      * "; echo ${blue}"formatting home partition..."${normal}; sleep 0.5s' >> format.eg
        file_format; file_fstab
        echo 'echo -n ${red} "      * "; echo ${blue}"mounting home partition..."${normal}; sleep 0.5s' >> mount.eg
        file_mount
    fi

    if [ -n "$(grep '^extra ' ${profile})" ]; then
        grep '^extra ' ${profile} > extra.eg
        dp="0 0"
        
        echo 'echo -n ${red} "      * "; echo ${blue}"formatting other specified partitions..."${normal}; sleep 0.5s' >> format.eg
        
        while read name part label fs mp
        do
            file_format; file_fstab
        done < extra.eg
        
        echo 'echo -n ${red} "      * "; echo ${blue}"mounting other specified partitions..."${normal}; sleep 0.5s' >> mount.eg
        
        while read name part label fs mp
        do
            file_mount
        done < extra.eg
    fi
    
    echo "shm    /dev/shm    tmpfs    nodev,nosuid,noexec    0 0"  >> fstab.eg

    chmod +x format.eg; chmod +x mount.eg
    
    settings="arch blimit domainname grub hostname keymap rootpass setup type userpass username windows"

    for s in ${settings}
    do
        unset value value2
        if [ -z "$(grep ^${s} ${profile})" ]; then
            default_value "${s}"
        else
            grep "^${s} " ${profile} > p.tmp
            
            value="$(awk '{print $2}' p.tmp)"
            
            case ${s} in
            arch)
                case ${value} in
                i686|amd64)
                    e="x"
                ;;
                32|32bit|"32 bit")
                    value="i686"
                ;;
                64|64bit|"64 bit")
                    value="amd64"
                ;;
                *)
                    default_value "${s}"
                ;;
                esac
            ;;
            blimit)
                case ${value} in
                [0-9] | [0-9][0-9] | [0-9][0-9][0-9])
                    e="x"
                ;;
                [0-9][0-9][0-9][0-9] | [0-9][0-9][0-9][0-9][0-9])
                    e="x"
                ;;
                *)
                    default_value "${s}"
                ;;
                esac
            ;;
            grub)
                case ${value} in
                [s:h]d[a-z] | [s:h]d[a-z][1-9] | [s:h]d[a-z][1-9][0-9] | [s:h]d[a-z][1-9][0-9][0-9])
                    e="x"
                ;;
                *)
                    default_value "${s}"
                ;;
                esac
            ;;
            keymap)
                case ${value} in
                br|trq|trf|us)
                    e="x"
                ;;
                tr)
                    value="trq"
                ;;
                *)
                    default_value "${s}"
                ;;
                esac
            ;;
            setup)
                case ${value} in
                basic|normal)
                    e="x"
                ;;
                *)
                    default_value "${s}"
                ;;
                esac
            ;;
            type)
                case ${value} in
                laptop|pc)
                    e="x"
                ;;
                *)
                    default_value "${s}"
                ;;
                esac
            ;;
            esac
        fi
        
        [[ -n "${value}" ]] && a2v "${s}=\"${value}\""
    done
    
    core=$(grep -c processor /proc/cpuinfo)
    a2v "core=\"${core}\""

    case ${arch} in
    i686)
        kw="x86"
    ;;
    amd64)
        kw="amd64"
    ;;
    esac
    
    a2v "kw=\"${kw}\""

    case ${disk_size} in
    [1-9] | [1-9][0-9] | [1-9][0-9][0-9] | [2-5][0-9][0-9][0-9])
        echo; er "root partition (${root_part}) is smaller (${disk_size} MB) than the recommended partition size (6000 MB)."
        echo; er "This may cause some problems during setup. It is safer to choose/create a bigger partition for root."
        er "Press any key if you want to ignore this and continue..."; echo; read key
    ;;
    esac

    find_flags
    fdisk -l /dev/"${root_part}" 2>/dev/null | grep "${root_part}" | tr ':,' '\n' | grep -v "bytes" | grep -v "${root_part}" | grep "[0-9] [A-Z]" > psize.tmp
    
    while read g1 g2
    do
        psize="${g1}"
        stype="${g2}"
    done < psize.tmp
    
    psize="$(echo ${psize} | cut -d'.' -f1)"
    ram_size="$(grep -i memtotal < /proc/meminfo | sed -e 's:.* \([0-9].* kb\):\1:i' -e 's: .*::')"
    
    a2v "psize=\"${psize}\"   stype=\"${stype}\"   ram_size=\"${ram_size}\""
    
    echo; eb2 "* "; eg2 "Preparing partitions... "; ey "(formatting)"; echo; sleep 0.5s; ./format.eg
    echo; eb2 "* "; eg2 "Preparing partitions... "; ey "(mounting)"; echo; sleep 0.5s; ./mount.eg
    rm -rf format.eg mount.eg p.tmp psize.tmp
}

get_tar() {
    [[ "$(ping -nc1 www.google.com)" ]] && tch connected.eg || { [[ "$(ping -nc3 www.google.com)" ]] && tch connected.eg || connect_me &>/dev/null; }
    echo; eb2 "* "; eg "Checking mirrors..."; sleep 0.5s
    
    case ${keymap} in
    trq|trf)
        mirrorlist="http://ftp.linux.org.tr/gentoo ftp://ftp.linux.org.tr/gentoo ftp://mirrors.linuxant.fr/distfiles.gentoo.org"
    ;;
    br|us)
        mirrorlist="ftp://mirrors.linuxant.fr/distfiles.gentoo.org http://gentoo.supp.name"
    ;;
    esac
    
    a2v "mirrorlist=\"${mirrorlist}\""
    
    mirror_check
    timesync
    
    # [[ -e "${lt}" ]] && rm -rf ${lt}
    
    # echo; eb2 "* "; eg "Getting latest tarball name..."; sleep 1s
    
    # case ${arch} in
    # i686)
        # get_files "${mirror}/releases/x86/autobuilds/${lt}"
    # ;;
    # amd64)
        # get_files "${mirror}/releases/amd64/autobuilds/${lt}"
    # ;;
    # esac
    
    # sed -i -e '\!^#!d' -e 's:^[ \t]*::' -e 's:[ \t]*$::' -e '\!^$!d' ${lt}
    
    # ext=".tar.bz2"
    # tardate="$(grep ${arch} ${lt} | cut -d'/' -f1 | uniq)"
    # tarball="stage3-${arch}-${tardate}${ext}"
    
    # a2v "tarball=\"${tarball}\""
    
    # en2 "  Latest tarball:"; ey "  ${tarball}"; sleep 1s
    
    # case ${arch} in
    # i686)
        # t_int="${mirror}/releases/x86/autobuilds/${tardate}/${tarball}"; t_dig="${t_int}.DIGESTS"
    # ;;
    # amd64)
        # t_int="${mirror}/releases/amd64/autobuilds/${tardate}/${tarball}"; t_dig="${t_int}.DIGESTS"
    # ;;
    # esac
    
    # Temporary fix for tarball download issue
    
    case ${arch} in
    i686)
        tarball="stage3-i686-20130305.tar.bz2"
        t_int="${mirror}/releases/x86/autobuilds/20130305/default/20130305/${tarball}"
    ;;
    amd64)
        tarball="stage3-amd64-20130321.tar.bz2"
        t_int="${mirror}/releases/amd64/autobuilds/20130321/default/20130321/${tarball}"
    ;;
    esac
    
    t_dig="${t_int}.DIGESTS"
    
    a2v "tarball=\"${tarball}\""
    
    check="x"
    while [ "${check}" != "ok" ]
    do
        [[ -e "${tarball}.DIGESTS" ]] && rm -rf ${tarball}.DIGESTS

        get_files "${t_dig}"; grep "${tarball}" "${tarball}.DIGESTS" | sed 1q > t_dig.eg

        if [ -e "${tarball}" ]; then
            echo; eb2 "* "; ew2 "stage3-${arch} tarball exists. "; eg "(previously downloaded)"
        else
            echo; eb2 "* "; er "Downloading stage3-${arch} tarball... "
            
            if [ "${blimit}" -gt "0" ]; then
                get_files "--limit-rate=${blimit}k ${t_int}"
            else
                get_files "${t_int}"
            fi
        fi
        
        ey2 "  Checking tarball integrity... "; shasum "t_dig.eg" "${tarball}"
    done
    
    echo "${tarball}" > tball.eg
    
    open_tar &
    
    p="portage-latest.tar.bz2"; p_md5="${p}.md5sum"; p_int="${mirror}/snapshots/${p}"

    check="x"
    while [ "${check}" != "ok" ]
    do
        [[ -e "${p_md5}" ]] && rm -rf ${p_md5}

        get_files "${mirror}/snapshots/${p_md5}"

        if [ -e "${p}" ]; then
            echo; eb2 "* "; ew2 "portage snapshot exists. "; eg "(previously downloaded)"
        else
            echo; eb2 "* "; er "Downloading portage snapshot... "
            
            if [ "${blimit}" -gt "0" ]; then
                get_files "--limit-rate=${blimit}k ${p_int}"
            else
                get_files "${p_int}"
            fi
        fi
        
        ey2 "  Checking portage snapshot integrity... "; csum "${p_md5}" "${p}"
    done
    
    echo "${p}" > sshot.eg
    
    [[ ! -e "move.eg" ]] && { echo; eb2 "* "; ey "Extracting downloaded files, this may take a while..."; echo; }
    
    while true
    do
        [[ -e "tball.done" ]] && { read t < tball.eg; eg2 "  ${t}"; ew " is successfully extracted."; break; } || sleep 1s
    done
    
    while true
    do
        [[ -e "sshot.done" ]] && { read p < sshot.eg; eg2 "  ${p}"; ew " is successfully extracted."; break; } || sleep 1s
    done

    until [ -e "move.eg" ]
    do
        sleep 1s
    done
    
    rm -rf tball.* sshot.* move.eg
}

open_tar() {
    echo
    until [ -e "tball.eg" ]
    do
        sleep 1s
    done
    
    read t < tball.eg
    tar xjpf ${t} -C ${mnt} && touch tball.done
    
    until [ -e "sshot.eg" ]
    do
        sleep 1s
    done
    
    read p < sshot.eg
    mkdir -p ${mnt}/usr/portage && tar xjf ${p} -C ${mnt}/usr && touch sshot.done

    touch move.eg
}

move() {
    cp -dpRL /dev/{console,kmem,mem,null,urandom,random,zero,ptmx,ram[0-6],tty[0-6]} ${mnt}/dev &>/dev/null
    
    [[ -e "${mnt}/etc/resolv.conf" ]] && cp ${mnt}/etc/resolv.conf ${mnt}/etc/resolv.conf.backup && rm -rf ${mnt}/etc/resolv.conf
    
    cp -L /etc/resolv.conf ${mnt}/etc/

    [[ ! -d "${mnt}/etc/portage" ]] && mkdir -p ${mnt}/etc/portage

    umount -l ${mnt}/proc ${mnt}/dev &>/dev/null
    mount -t proc none ${mnt}/proc &>/dev/null
    mount -R /dev ${mnt}/dev &>/dev/null
    
    cp ${eg} ${mnt} &>/dev/null
    mv ${profile} ${mnt} &>/dev/null
    mv ${compiled} ${mnt} &>/dev/null
    mv ${vl} ${mnt} &>/dev/null
    mv *.tar.bz2 ${mnt} &>/dev/null
    mv *.eg ${mnt} &>/dev/null
    mv *.tmp ${mnt} &>/dev/null
    
    rm -rf easygentoo.config *.DIGESTS *.eg *.md5sum *.tmp ${lt} ${vl}
    
    touch ${mnt}/chroot.eg &>/dev/null
    
    chroot ${mnt} sh ${eg}
}

create_swap_file() {
    case ${stype} in
    MB)
        [[ "${psize}" -gt "8000" ]] && swap_file="yes"
    ;;
    GB)
        [[ "${psize}" -gt "8" ]] && swap_file="yes"
    ;;
    TB)
        swap_file="yes"
    ;;
    *)
        swap_file="no"
    ;;
    esac
    
    case ${swap_file} in
    yes)
        echo; eb2 "* "; eg2 "Creating a swap file"; er " (1GB)"; sleep 0.5s
        dd if=/dev/zero of=/egswap count=2M &>/dev/null
        mkswap /egswap &>/dev/null
        swapon /egswap &>/dev/null
    ;;
    esac
}

shut() {
    [[ -e "stop.eg" ]] && break
}

inside() {
    [[ -e stop.eg ]] && rm -rf stop.eg
    [[ ! -e "${compiled}" ]] && touch ${compiled}
    on_off &
    net_watch &
    
    echo; eg "  !!--Chroot--!!"
    timesync
    
    fl "/etc/etc-update.conf" "0" "0"
    
    avoid_dup 'rm_opts=""'
    avoid_dup 'cp_opts=""'

    refresh
    
    [[ -z "${swap_part}" ]] && (( "${ram_size}" < "1900000" )) && create_swap_file
    
    case ${type} in
    pc)
        echo 10 > /proc/sys/vm/swappiness
        echo 600 > /proc/sys/vm/dirty_expire_centisecs
        echo 600 > /proc/sys/vm/dirty_writeback_centisecs
        echo 5 > /proc/sys/vm/dirty_background_ratio
        echo 20 > /proc/sys/vm/dirty_ratio
        echo 0 > /proc/sys/vm/laptop_mode
        echo 50 > /proc/sys/vm/vfs_cache_pressure
    ;;
    laptop)
        echo 10 > /proc/sys/vm/swappiness
        echo 50 > /proc/sys/vm/vfs_cache_pressure
    ;;
    esac
    
    echo; eb2 "* "; eg2 "Creating"; er " make.conf..."; sleep 0.5s

    fl "/etc/portage/make.conf" "0" "d"

    cf "CFLAGS=\"-march=native -O2 -pipe\""
    cf 'CXXFLAGS="${CFLAGS}"'
        case ${arch} in
        i686)
            cf 'CHOST="i686-pc-linux-gnu"'
        ;;
        amd64)
            cf 'CHOST="x86_64-pc-linux-gnu"'
        ;;
        esac
    cf 'LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--sort-common -Wl,--hash-style=gnu"'
    cf 'ACCEPT_KEYWORDS="'${kw}'"'
    cf 'ACCEPT_LICENSE="*"'
    cf 'MAKEOPTS="-j2"'
        case ${keymap} in
        br)
            cf 'LINGUAS="pt_BR"'
        ;;
        trq|trf)
            cf 'LINGUAS="tr en"'
        ;;
        us)
            cf 'LINGUAS="en"'
        ;;
        esac
    cf 'AUTOCLEAN="no"'
    cf 'FEATURES="-ccache -distcc fixlafiles -news -parallel-fetch sandbox userpriv usersandbox"'
    cf 'USE="'${available_cpu_flags}'"'
    cf ''
    cf '# It is recommended to leave WANT_MP disabled because of the problems it may trigger.'
    cf '# WANT_MP="true"'
    cf ''
    cf 'PORTAGE_RSYNC_INITIAL_TIMEOUT="10"'
    cf 'PORTAGE_RSYNC_RETRIES="5"'
    cf 'GENTOO_MIRRORS="'${mirrorlist}'"'
    cf 'RSYNC="rsync://rsync2.us.gentoo.org rsync://rsync3.us.gentoo.org rsync://rsync25.us.gentoo.org"'
        if [ "${blimit}" -gt "0" ]; then
            cf 'FETCHCOMMAND="${FETCHCOMMAND} --limit-rate='${blimit}'k"'
            cf 'RESUMECOMMAND="${RESUMECOMMAND} --limit-rate='${blimit}'k"'
        fi
    cf 'EMERGE_DEFAULT_OPTS="--autounmask=y --autounmask-write=y --with-bdeps=y --quiet-build"'
    cf ''
    
    mkdir -p /etc/portage/env/dev-lang
    mkdir -p /etc/portage/env/dev-db
    mkdir -p /etc/portage/env/www-client
    mkdir -p /etc/portage/env/net-libs
    
    fl "/etc/portage/env/O3-cflags" "0" "d"
    cf "CFLAGS=\"-march=native -O3 -pipe\""
    cf 'CXXFLAGS="${CFLAGS}"'
    
    ln -sf /etc/portage/env/O3-cflags /etc/portage/env/dev-lang/python &>/dev/null
    ln -sf /etc/portage/env/O3-cflags /etc/portage/env/dev-db/sqlite &>/dev/null
    
    fl "/etc/portage/env/firefox-cflags" "0" "d"
    cf "CFLAGS=\"-march=native -Os -pipe -fomit-frame-pointer\""
    cf 'CXXFLAGS="${CFLAGS}"'
    cf 'LDFLAGS="${LDFLAGS} -Bdirect -Wl,-z,now"'
    
    ln -sf /etc/portage/env/firefox-cflags /etc/portage/env/www-client/firefox &>/dev/null
    
    fl "/etc/portage/env/xulrunner-cflags" "0" "d"
    cf "CFLAGS=\"-march=native -O2 -pipe -fomit-frame-pointer\""
    cf 'CXXFLAGS="${CFLAGS}"'
    cf 'LDFLAGS="${LDFLAGS} -Bdirect -Wl,-z,now"'
    
    ln -sf /etc/portage/env/xulrunner-cflags /etc/portage/env/net-libs/xulrunner &>/dev/null
    
    echo; k_portage; k_must
    
    fl "/etc/locale.gen" "0" "0"
    
    case ${keymap} in
    br)
        cf "pt_BR.UTF-8 UTF-8"
        cf "pt_BR ISO-8859-1"
    ;;
    trq|trf)
        cf "tr_TR.UTF-8 UTF-8"
        cf "tr_TR ISO-8859-9"
    ;;
    us)
        cf "en_US.UTF-8 UTF-8"
        cf "en_US ISO-8859-1"
    ;;
    esac
    
    locale-gen &>/dev/null
    
    echo; eb2 "* "; eg2 "Updating"; er " make.conf..."; sleep 0.5s

    fl "/etc/portage/make.conf" "0" "d"

    cf "CFLAGS=\"-march=native -O2 -pipe\""
    cf 'CXXFLAGS="${CFLAGS}"'
        case ${arch} in
        i686)
            cf 'CHOST="i686-pc-linux-gnu"'
        ;;
        amd64)
            cf 'CHOST="x86_64-pc-linux-gnu"'
        ;;
        esac
    cf 'LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--sort-common -Wl,--hash-style=gnu"'
    cf 'ACCEPT_KEYWORDS="'${kw}'"'
    cf 'ACCEPT_LICENSE="*"'
    cf 'MAKEOPTS="-j'${core}'"'
    cf ''
    cf '# It is recommended to leave WANT_MP disabled because of the problems it may trigger.'
    cf '# WANT_MP="true"'
    cf ''
    
    cf '#cpu'
    cf 'USE="${USE} '${available_cpu_flags}'"'
    cf ''
    cf '#file systems'
    cf 'USE="${USE} btrfs fat hfs inotify jfs nfs ntfs reiser4 reiserfs sysfs xfs"'
    cf ''
    cf '#base system'
    cf 'USE="${USE} acl acpi bash-completion berkdb bidi bzip2 consolekit crypt css dbus '
    cf '    gnutls ipv6 kmod lzo ncurses nls nptl pam policykit profile rar readline '
    cf '    sqlite sqlite3 ssl symlink tcpd truetype udev unicode usb vdpau zlib"'
    cf ''
    cf '#toolchain'
    cf 'USE="${USE} fortran mudflap openmp"'
    cf ''
    cf '#disabled'
    cf 'USE="${USE} -apm -arts -avahi -beagle -branding -cpudetection -debug -dhclient -doc '
    cf '    -dso -eds -esd -evo -git -gdbm -gphoto2 -gpm -hal -hunspell -introspection -java '
    cf '    -joystick -kdeprefix -kerberos -ldap -minimal -mono -mysql -nss -openexr '
    cf '    -oss -perl -spell -static -static-libs -xscreensaver -zemberek"'
    cf ''
    cf '#printer'
    cf 'USE="${USE} -cups -foomaticdb -scanner"'
    cf ''
    cf '#laptop'
    
    case ${type} in
    laptop)
        cf 'USE="${USE} bluetooth ieee1394 irda laptop lm_sensors pcmcia wifi"'
    ;;
    pc)
        cf 'USE="${USE} -bluetooth -ieee1394 -irda -laptop -lm_sensors -pcmcia -wifi"'
    ;;
    esac
    
    cf ''
    cf '#internet'
    cf 'USE="${USE} -aim -icq -imap -irc -jabber -msn -oscar -rss -slp -yahoo"'
    cf ''
    
    case ${setup} in
    normal)
        cf '#codecs'
        cf 'USE="${USE} a52 aac avi dts dv encode ffmpeg flac gsm lame '
        cf '    mad matroska mp3 mp4 mpeg musepack ogg openal quicktime real '
        cf '    speex theora vorbis win32codecs x264 xvid"'
        cf ''
        cf '#multimedia'
        cf 'USE="${USE} alsa audiofile cdda cddb cdr dri dvb dvd dvdr '
        cf '    fam -jack ipod -mjpeg -mp3rtp -musicbrainz network -pulseaudio '
        cf '    sdl -v4l -v4l2 vcd vpx -wmf -xine"'
        cf ''
        cf '#X'
        cf 'USE="${USE} cairo dga gif gtk opengl svg tiff X -xinerama xpm"'
        cf ''
        cf '#xfce'
        cf 'USE="${USE} startup-notification thunar xfce -gnome -kde '
        cf '    -nautilus -qt3support -qt4"'
    ;;
    basic)
        cf '#codecs'
        cf 'USE="${USE} -a52 -aac -avi -dts -dv -encode -ffmpeg -flac '
        cf '    -gsm -lame -mad -matroska -mp3 -mp4 -mpeg -musepack -ogg -openal '
        cf '    -quicktime -real -speex -theora -vorbis -win32codecs -x264 -xvid"'
        cf ''
        cf '#multimedia'
        cf 'USE="${USE} alsa -audiofile -cdda -cddb cdr dri -dvb dvd '
        cf '    dvdr fam -jack -ipod -mjpeg -mp3rtp -musicbrainz network -pulseaudio '
        cf '    sdl -v4l -v4l2 -vcd -vpx -wmf -xine"'
        cf ''
        cf '#X'
        cf 'USE="${USE} -cairo -dga -gif -gtk -opengl -svg -tiff -X -xinerama -xpm"'
        cf ''
        cf '#no desktop environment'
        cf 'USE="${USE} -gnome -kde -nautilus -qt3support -qt4 '
        cf '    -startup-notification -thunar -xfce"'
    ;;
    esac
    
    cf ''
    
    case ${arch} in
    amd64)
        cf '#64bit'
        cf 'USE="${USE} multilib"'
        cf ''
    ;;
    esac
    
    cf 'VIDEO_CARDS="dummy fbdev vesa"'
    
    case ${type} in
    pc)
        cf 'INPUT_DEVICES="evdev"'
    ;;
    laptop)
        cf 'INPUT_DEVICES="evdev synaptics"'
    ;;
    esac
    
        case ${keymap} in
        br)
            cf 'LINGUAS="pt_BR"'
        ;;
        trq|trf)
            cf 'LINGUAS="tr"'
        ;;
        us)
            cf 'LINGUAS="en"'
        ;;
        esac
    cf 'AUTOCLEAN="yes"'
    cf 'CONFIG_PROTECT="/etc /etc/fstab /etc/hosts /etc/locale.gen '
    cf '    /etc/localtime /etc/rc.conf /etc/sudoers /etc/sysctl.conf '
    cf '    /etc/X11/xorg.conf.d /etc/portage/package.use /etc/conf.d/domainname '
    cf '    /etc/conf.d/hostname /etc/conf.d/hwclock /etc/conf.d/keymaps '
    cf '    /etc/conf.d/net /etc/modprobe.d/blacklist.conf /etc/portage/env '
    cf '    /etc/X11/gdm /usr/share/config/kdm"'
    cf 'PORTDIR="/usr/portage"'
    cf 'PORTAGE_TMPDIR="/var/tmp"'
    cf 'PORTAGE_COMPRESS="bzip2"'
    cf 'PORTAGE_COMPRESS_FLAGS="-9"'
    cf 'PORTAGE_NICENESS="15"'
    cf 'PORTAGE_RSYNC_INITIAL_TIMEOUT="10"'
    cf 'PORTAGE_RSYNC_RETRIES="5"'
    cf 'FEATURES="-ccache -distcc fixlafiles -news -parallel-fetch sandbox userpriv usersandbox"'
    cf 'GENTOO_MIRRORS="'${mirrorlist}'"'
    cf 'RSYNC="rsync://rsync2.us.gentoo.org rsync://rsync3.us.gentoo.org rsync://rsync25.us.gentoo.org"'
        if [ "${blimit}" -gt "0" ]; then
            cf 'FETCHCOMMAND="${FETCHCOMMAND} --limit-rate='${blimit}'k"'
            cf 'RESUMECOMMAND="${RESUMECOMMAND} --limit-rate='${blimit}'k"'
        fi
    cf 'EMERGE_DEFAULT_OPTS="--autounmask=y --autounmask-write=y --with-bdeps=y --quiet-build"'
        case ${setup} in
        normal)
            case ${type} in
            laptop)
                cf 'XFCE_PLUGINS="brightness menu trash"'
            ;;
            pc)
                cf 'XFCE_PLUGINS="menu trash"'
            ;;
            esac
        ;;
        esac
    cf ''

    echo; eb2 "* "; eg2 "Creating"; er " package.use..."; sleep 0.5s

    fl "/etc/portage/package.use" "b" "d"

    cf "app-admin/conky hddtemp imlib mpd truetype weather-metar -wifi"
    cf "app-admin/gnome-system-tools nfs policykit"
    cf "app-admin/system-tools-backends policykit"
    cf "app-cdr/k3b alsa css dvd dvdr dvdread encode ffmpeg flac mp3 musepack musicbrainz vcd vorbis"
    cf "app-cdr/recorder dvdr vcd"
    cf "app-emulation/bochs vnc wxwidgets"
    cf "app-emulation/emul-linux-x86-java alsa X nsplugin"
    cf "app-emulation/libvirt network uml virtualbox libvirtd qemu"
    cf "app-emulation/wine fontconfig gphoto2"
    cf "app-office/abiword -collab openxml -plugins wordperfect"
    cf "app-office/gnumeric -perl -python"
    cf "app-office/lyx docbook dot html latex rtf dia"
    cf "app-office/planner libgda"
    cf "app-text/acroread nsplugin"
    cf "app-text/docbook-sgml-utils jadetex"
    cf "app-text/enchant aspell"
    cf "app-text/evince dvi t1lib"
    cf "app-text/tesseract tiff"
    cf "dev-db/mysql embedded"
    cf "dev-java/sun-jre-bin nsplugin"
    cf "dev-java/swt firefox"
    cf "dev-lang/perl ithreads"
    cf "dev-lang/python threads"
    cf "dev-lang/spidermonkey threadsafe"
    cf "dev-lang/swig guile"
    cf "dev-libs/glib -fam"
    cf "dev-libs/libcdio cddb"
    cf "dev-libs/libxml2 python"
    cf "dev-libs/libxslt crypt python"
    cf "dev-libs/xmlrpc-c curl libwww"
    cf "dev-python/PyQt4 sql webkit kde multimedia"
    cf "dev-python/pycairo numeric"
    cf "dev-vcs/git curl webdav -gtk"
    cf "games-board/pysolfc extra-cardsets"
    cf "games-engines/scummvm fluidsynth"
    cf "games-fps/quake3-data cdinstall"
    cf "games-strategy/ufo-ai doc editor"
    cf "games-strategy/wesnoth doc"
    cf "gnome-base/gdm remote consolekit"
    cf "gnome-base/gnome-applets gstreamer networkmanager policykit"
    cf "gnome-base/gnome-session branding"
    cf "gnome-base/gvfs fuse gdu -gphoto2 -http"
    cf "gnome-base/librsvg nsplugin"
    cf "gnome-extra/gnome-games artworkextra guile"
    cf "gnome-extra/libgsf thumbnail"
    cf "gnome-extra/nautilus-sendto -bluetooth"
    cf "gnustep-base/gnustep-back-cairo -glitz"
    cf "kde-base/dolphin thumbnail"
    cf "kde-base/kdelibs acl alsa semantic-desktop"
    cf "kde-base/kdebase-startkde xinerama"
    cf "kde-base/kdenetwork-meta -ppp"
    cf "kde-base/kdm consolekit"
    cf "kde-base/kopete -jingle msn oscar ssl yahoo"
    cf "kde-base/konqueror branding java thumbnail"
    cf "kde-base/okular djvu ebook jpeg pdf tiff"
    cf "kde-base/plasma-workspace -python"
    cf "kde-base/solid networkmanager"
    cf "media-gfx/blender blender-game"
    cf "media-gfx/digikam gphoto2"
    cf "media-gfx/gimp alsa curl dbus gimpprint gtkhtml jpeg mmx mng png python sse svg tiff"
    cf "media-gfx/gthumb gphoto2"
    cf "media-gfx/imagemagick -perl"
    cf "media-gfx/inkscape dia effects inkjar plugin postscript"
    cf "media-gfx/sane-backends gphoto2"
    cf "media-gfx/splashutils fbcondecor"
    cf "media-gfx/xsane gimp"
    cf "media-libs/clutter introspection"
    cf "media-libs/gd fontconfig jpeg png xpm"
    cf "media-libs/imlib2 nls zlib X"
    cf "media-libs/libcanberra gtk"
    cf "media-libs/libgphoto2 exif"
    cf "media-libs/libpng apng"
    cf "media-libs/libquicktime schroedinger"
    cf "media-libs/libvorbis aotuv"
    cf "media-libs/mesa g3dvl gallium llvm -motif pic vdpau xcb"
    cf "media-libs/phonon gstreamer"
    cf "media-libs/sdl-mixer midi mikmod timidity"
    cf "media-libs/sdl-sound physfs"
    cf "media-libs/urt gs"
    cf "media-libs/xine-lib dts imagemagick mng modplug vcd vidix xcb xvmc"
    cf "media-libs/win32codecs real"
    cf "media-plugins/alsa-plugins -pulseaudio"
    cf "media-plugins/audacious-plugins fluidsynth midi modplug musepack sid timidity wma"
    cf "media-sound/amarok embedded ipod lastfm mp3tunes"
    cf "media-sound/audacity midi id3tag twolame soundtouch"
    cf "media-sound/banshee ipod youtube wikipedia"
    cf "media-sound/lame -gtk"
    cf "media-sound/pulseaudio -avahi glib gnome"
    cf "media-sound/rhythmbox ipod musicbrainz upnp"
    cf "media-sound/sox id3tag"
    cf "media-sound/xmms2 -java -python -samba"
    cf "media-tv/freevo dvd gphoto2"
    cf "media-tv/linuxtv-dvb-apps -usb"
    cf "media-tv/mythtv lcd"
    cf "media-video/avidemux -qt4 alsa aac dts encode fontconfig gtk lame truetype vorbis x264 xv xvid"
    cf "media-video/chaplin transcode vcd"
    cf "media-video/dvdrip vcd subtitles"
    cf "media-video/ffmpeg -altivec amr dirac encode faac faad schroedinger theora threads v4l v4l2 vaapi vorbis -X x264 xvid"
    cf "media-video/gpac amr"
    cf "media-video/gnome-mplayer ipod"
    cf "media-video/gxine xcb"
    cf "media-video/mjpegtools yv12"
    cf "media-video/mplayer a52 aac aalib -altivec ass -cpudetection dts dvd -dxr3 encode faac -ipv6 mp3 quicktime real -samba theora truetype unicode v4l v4l2 vidix vorbis win32codecs X x264 xv xvid"
    cf "media-video/ogmrip ogm srt"
    cf "media-video/smplayer linguas_tr"
    cf "media-video/totem nsplugin"
    cf "media-video/transcode a52 -altivec dvd iconv imagemagick lzo mjpeg mp3 mpeg nuv ogg postproc quicktime vorbis xvid"
    cf "media-video/vlc a52 aac aalib -altivec dirac dvd ffmpeg flac fluidsynth fontconfig id3tag libass mp3 mpeg ogg opengl -samba schroedinger theora truetype twolame upnp v4l v4l2 vaapi vorbis win32codecs wma-fixed x264 xcb xv"
    cf "media-video/winki css dvd matroska mjpeg mp3 ogg vcd"
    cf "net-dialup/ppp atm ipv6"
    cf "net-dns/avahi autoipd mdnsresponder-compat"
    cf "net-dns/pdns-recursor lua"
    cf "net-nds/openldap gnutls"
    cf "net-fs/samba automount"
    cf "net-im/pidgin -gstreamer -perl -python"
    cf "net-irc/irssi -perl"
    cf "net-libs/libproxy -gnome -xulrunner"
    cf "net-libs/opal sip"
    cf "net-libs/ptlib wav"
    cf "net-misc/curl -ares gnutls libssh2 ldn"
    cf "net-misc/dhcp minimal"
    cf "net-misc/networkmanager connection-sharing dhcpcd resolvconf wext"
    cf "net-misc/ntp caps opentpd -ipv6"
    cf "net-misc/nxserver-freenx nxclient"
    cf "net-misc/wicd -pm-utils"
    cf "net-print/cups acl gnutls pam -perl ppds -python samba ssl"
    cf "net-print/gutenprint gimp ppds"
    cf "net-print/hplip minimal ppds scanner"
    cf "net-wireless/wpa_supplicant eap-sim ps3 -fasteap madwifi wimax wps"
    cf "sci-astronomy/stellarium stars"
    cf "sci-visualization/gnuplot gd -pdf"
    cf "sys-apps/dbus X"
    cf "sys-apps/help2man -nls"
    cf "sys-apps/iproute2 -minimal"
    cf "sys-apps/pciutils -zlib"
    cf "sys-apps/pmount crypt"
    cf "sys-apps/shadow -pam"
    cf "sys-auth/consolekit policykit"
    cf "sys-auth/pambase consolekit"
    cf "sys-block/parted device-mapper"
    cf "sys-block/gparted dmraid fat hfs jfs mdadm ntfs reiser4 reiserfs xfs"
    cf "sys-devel/gcc -gtk -objc"
    cf "sys-devel/libperl ithreads"
    cf "sys-fs/ntfs3g acl ntfsprogs -external-fuse -suid"
    cf "sys-fs/udev extras"
    cf "sys-kernel/genkernel bash-completion"
    cf "sys-libs/glibc glibc-omitfp nptl nptlonly userlocales"
    cf "sys-power/cpufreqd acpi -lm_sensors"
        case ${arch} in
        i686)
            cf "www-plugins/adobe-flash 32bit -64bit"
        ;;
        amd64)
            cf "www-plugins/adobe-flash -32bit 64bit multilib"
        ;;
        esac
    cf "www-client/firefox -bindist custom-optimization -java linguas_tr"
    cf "www-client/opera qt-static"
    cf "x11-apps/xinit minimal"
    cf "x11-base/xorg-server kdrive -minimal xorg"
    cf "x11-drivers/nvidia-drivers gtk"
    cf "x11-libs/cairo cleartype -glitz xcb"
    cf "x11-libs/libX11 xcb"
    cf "x11-libs/qt-core optimized-qmake"
    cf "x11-misc/pcmanfm -gnome"
    cf "x11-misc/rss-glx -xscreensaver"
    cf "x11-misc/slim branding"
    cf "x11-misc/xscreensaver new-login -perl"
    cf "x11-terms/rxvt-unicode -perl"
    cf "x11-terms/aterm background"
    cf "x11-terms/xterm toolbar"
    cf "x11-wm/compiz fuse"
    cf "x11-wm/compiz-fusion emerald"
    cf "x11-wm/dwm savedconfig"
    cf "x11-wm/enlightenment xcomposite xrandr"
    cf "x11-wm/fluxbox -gnome -kde truetype -vim-syntax"
    cf "x11-wm/fvwm gtk2-perl netpbm"
    cf "x11-wm/windowmaker gnustep"
    cf "xfce-base/thunar -pcre xfce_plugins_trash"
    cf "xfce-base/xfdesktop thunar"
    cf "xfce-extra/xfce4-sensors-plugin hddtemp lm_sensors"

    dlt "/etc/make.conf"
    
    k_system
    k_kernel
    
    case "${grub}" in
    none)
        e="x"
    ;;
    [s:h]d[a-z] | [s:h]d[a-z][1-9] | [s:h]d[a-z][1-9][0-9] | [s:h]d[a-z][1-9][0-9][0-9])
        k_grub
    ;;
    esac
    
    k_needed
    
    case ${setup} in
    normal)
        k_x; k_nm; k_alsa
    ;;
    esac
    
    echo; eb2 "* "; eg "Creating/Updating necessary configuration files..."; sleep 1s
    refresh

    liste="/etc/fstab /etc/hosts /etc/locale.gen /etc/localtime /etc/rc.conf /etc/sysctl.conf /etc/conf.d/domainname /etc/conf.d/hostname /etc/conf.d/hwclock /etc/conf.d/keymaps /etc/conf.d/net /etc/modprobe.d/blacklist.conf"

    for d in ${liste}
    do
        echo; er2 "      * "; eg "${d}"; sleep 0.5s
        
        case ${d} in
        /etc/conf.d/domainname|/etc/localtime)
            fl "${d}" "0" "d"
        ;;
        /etc/sysctl.conf)
            fl "${d}" "b" "d"
        ;;
        *)
            fl "${d}" "0" "0"
        ;;
        esac
        
        case ${d} in
        /etc/fstab)
            cp fstab.eg ${d}
        ;;
        /etc/hosts)
            sed -i s:"^127.0.0.1.*":"127.0.0.1    ${hostname}.${domainname} ${hostname} localhost": ${d}
        ;;
        /etc/locale.gen)
            case ${keymap} in
            br)
                cf "pt_BR.UTF-8 UTF-8"
                cf "pt_BR ISO-8859-1"
            ;;
            trq|trf)
                cf "tr_TR.UTF-8 UTF-8"
                cf "tr_TR ISO-8859-9"
            ;;
            us)
                cf "en_US.UTF-8 UTF-8"
                cf "en_US ISO-8859-1"
            ;;
            esac
            
            locale-gen &>/dev/null
        ;;
        /etc/localtime)
            case ${keymap} in
            br)
                ln -s /usr/share/zoneinfo/America/Sao_Paulo ${d}
                echo "America/Sao_Paulo" > /etc/timezone
            ;;
            trq|trf)
                ln -s /usr/share/zoneinfo/Europe/Istanbul ${d}
                echo "Europe/Istanbul" > /etc/timezone
            ;;
            us)
                ln -s /usr/share/zoneinfo/UTC ${d}
                echo "UTC" > /etc/timezone
            ;;
            esac
        ;;
        /etc/rc.conf)
            avoid_dup 'rc_hotplug="!net.*"'
            avoid_dup 'rc_logger="NO"'
            avoid_dup 'unicode="YES"'
            avoid_dup 'rc_sys=""'
            avoid_dup 'rc_tty_number=12'
            avoid_dup 'dbus_enable="YES"'
            avoid_dup 'hald_enable="NO"'
        ;;
        /etc/sysctl.conf)
            cf '## TCP SYN cookie protection'
            cf '## helps protect against SYN flood attacks'
            cf '## only kicks in when net.ipv4.tcp_max_syn_backlog is reached'
            cf 'net.ipv4.tcp_syncookies = 1'
            cf '## if not functioning as a router, there is no need to accept redirects or source routes'
            cf 'net.ipv4.conf.all.accept_redirects = 0'
            cf 'net.ipv4.conf.all.accept_source_route = 0'
            cf 'net.ipv4.conf.all.secure_redirects = 1'
            cf '## send redirects (not a router, disable it)'
            cf 'net.ipv4.conf.all.send_redirects = 0'
            cf '## Disable packet forwarding'
            cf 'net.ipv4.ip_forward = 0'
            cf '## protect against tcp time-wait assassination hazards'
            cf '## drop RST packets for sockets in the time-wait state'
            cf '## (not widely supported outside of linux, but conforms to RFC)'
            cf 'net.ipv4.tcp_rfc1337 = 1'
            cf '## source address verification (sanity checking)'
            cf '## helps protect against spoofing attacks'
            cf 'net.ipv4.conf.all.rp_filter = 1'
            cf 'net.ipv4.conf.default.rp_filter = 1'
            cf '## log martian packets'
            cf 'net.ipv4.conf.all.log_martians = 1'
            cf '## ignore echo broadcast requests to prevent being part of smurf attacks'
            cf 'net.ipv4.icmp_echo_ignore_broadcasts = 1'
            cf '## ignore bogus icmp errors'
            cf 'net.ipv4.icmp_ignore_bogus_error_responses = 1'
            cf ''
            cf 'vm.min_free_kbytes = 16384'
            
            case ${type} in
            pc)
                cf "vm.swappiness = 30"
                cf "vm.dirty_expire_centisecs = 600"
                cf "vm.dirty_writeback_centisecs = 600"
                cf "vm.dirty_background_ratio = 5"
                cf "vm.dirty_ratio = 20"
                cf "vm.laptop_mode = 0"
                cf "vm.vfs_cache_pressure = 50"
            ;;
            laptop)
                cf "vm.swappiness = 10"
                cf "vm.vfs_cache_pressure = 50"
            ;;
            esac
            
            sysctl -p &>/dev/null
        ;;
        /etc/conf.d/domainname)
            avoid_dup 'DNSDOMAIN="'${domainname}'"'
            avoid_dup 'NISDOMAIN="'${domainname}'"'
        ;;
        /etc/conf.d/hostname)
            avoid_dup 'hostname="'${hostname}'"'
        ;;
        /etc/conf.d/hwclock)
            [[ -n "${windows}" ]] && avoid_dup 'clock="local"' || avoid_dup 'clock="UTC"'
            avoid_dup 'clock_systohc="YES"'
            avoid_dup 'clock_hctosys="YES"'
            avoid_dup 'clock_args=""'
        ;;
        /etc/conf.d/keymaps)
            case ${keymap} in
            br)
                avoid_dup 'keymap="br-abnt2"'
            ;;
            *)
                avoid_dup 'keymap="'${keymap}'"'
            ;;
            esac
            
            avoid_dup 'windowkeys="YES"'
        ;;
        /etc/conf.d/net)
            avoid_dup 'dns_domain_lo="gentoo.powered"'
            
            for adapter in ${adapters_found}
            do
                avoid_dup 'auto_'${adapter}'="true"'
                avoid_dup 'config_'${adapter}'="dhcp"'
                avoid_dup 'dhcpcd_'${adapter}'="-t 10"'
                avoid_dup 'mtu_'${adapter}'="1492"'
                avoid_dup 'enable_ipv6_'${adapter}'="false"'
            done
        ;;
        /etc/modprobe.d/blacklist.conf)
            for d in amd76x_edac bcm43xx de4x5 dv1394 eepro100 eth1394 evbug \
            garmin_gps i2c_i801 ipv6 ite_cir net-pf-10 nouveau ohci1394 pcspkr \
            prism54 raw1394 sbp2 snd_aw2 snd_intel8x0m snd_pcsp usbkbd usblp \
            usbmouse video1394 wl  
            do
                cf "blacklist ${d}"
            done
            
            cf "# framebuffers"
            for e in aty128fb atyfb radeonfb cirrusfb cyber2000fb cyblafb gx1fb \
            hgafb i810fb intelfb kyrofb lxfb matroxfb_base neofb nvidiafb pm2fb \
            rivafb s1d13xxxfb savagefb sisfb sstfb tdfxfb tridentfb vesafb vfb \
            viafb vt8623fb
            do
                cf "blacklist ${e}"
            done
            
            cf "# modems"
            for f in snd-atiixp-modem snd-intel8x0m snd-via82xx-modem
            do
                cf "blacklist ${f}"
            done

            cf "# watchdog drivers"
            for g in acquirewdt advantechwdt alim1535_wdt alim7101_wdt booke_wdt \
            cpu5wdt eurotechwdt i6300esb i8xx_tco ib700wdt ibmasr indydog iTCO_wdt \
            it8712f_wdt it87_wdt ixp2000_wdt ixp4xx_wdt machzwd mixcomwd mpc8xx_wdt \
            mpcore_wdt mv64x60_wdt pc87413_wdt pcwd pcwd_pci pcwd_usb s3c2410_wdt \
            sa1100_wdt sbc60xxwdt sbc7240_wdt sb8360 sc1200wdt sc520_wdt sch311_wdt \
            scx200_wdt shwdt smsc37b787_wdt softdog twl4030_wdt w83627hf_wdt \
            w83697hf_wdt w83697ug_wdt w83877f_wdt w83977f_wdt wafer5823wdt wdt \
            wdt_pci wm8350_wdt
            do
                cf "blacklist ${g}"
            done
        ;;
        esac
    done
    
    echo; emerge --config timezone-data

    echo; eb2 "* "; eg "Configuring locale settings..."; sleep 0.5s
    
    [[ -e "/etc/env.d/02locale" ]] && { cp /etc/env.d/02locale /etc/env.d/02locale.backup; rm -rf /etc/env.d/02locale; }
    
    case ${keymap} in
    br)
        echo 'LANG="pt_BR.utf8"' > /etc/env.d/02locale
    ;;
    trq|trf)
        echo 'LANG="tr_TR.UTF-8"' > /etc/env.d/02locale
    ;;
    us)
        echo 'LANG="en_US.UTF-8"' > /etc/env.d/02locale
    ;;
    esac
    
    echo 'LC_COLLATE="C"' >> /etc/env.d/02locale
    
    fl "/etc/conf.d/consolefont" "0" "0"
    
    case ${keymap} in
    br)
        avoid_dup 'consolefont="lat9w-16"'
    ;;
    trq|trf)
        avoid_dup 'consolefont="iso09.16"'
    ;;
    us)
        avoid_dup 'consolefont="default8x16"'
    ;;
    esac
    
    rc-update add consolefont boot &>/dev/null

    echo; eb2 "* "; eg2 "Changing administrator "; er2 "(root)"; eg " password..."; sleep 0.5s

    echo "root:${rootpass}" | chpasswd

    echo; eb2 "* "; eg2 "Creating user "; er "${username}"; eg "..."; sleep 0.5s

    g_list="audio cdrom cdrw disk plugdev portage usb users video wheel"

    for g in ${g_list}; do
        c=$(grep "${g}" /etc/group | cut -d: -f1)
        
        case ${c} in
        ${g})
            [[ -z "${g_e}" ]] && g_e="${g}" || g_e="${g},${g_e}"
        ;;
        esac
    done

    useradd -m -G ${g_e} -s $(which bash) ${username}

    echo "${username}:${userpass}" | chpasswd
    
    if [ -e "/etc/sudoers" ]; then
        echo "%users   ALL=(root) ALL" >> /etc/sudoers
        echo "%users   ALL=(root) NOPASSWD: $(which shutdown)" >> /etc/sudoers
        echo "%users   ALL=(root) NOPASSWD: $(which reboot)" >> /etc/sudoers
        echo "%users   ALL=(root) NOPASSWD: $(which halt)" >> /etc/sudoers
        echo "%users   ALL=(root) NOPASSWD: $(which nano)" >> /etc/sudoers
        echo "%users   ALL=(root) NOPASSWD: $(which emerge)" >> /etc/sudoers
    fi

    lff
    
    [[ ! -e /home/${username}/.bash_profile ]] && cp /etc/skel/.bash_profile /home/${username}/
    
    echo export MOZ_DISABLE_PANGO=1 >> /home/${username}/.bash_profile

    fl "/home/${username}/.bashrc" "0" "0"

    cp /etc/skel/.bashrc ${trg_file}
    
    cf ""
    cf "export XDG_CONFIG_HOME=\"/home/${username}/.config\""
    cf "alias reboot='sudo shutdown -r now'"
    cf "alias halt='sudo halt -pi'"
    cf "alias shutdown='sudo shutdown -h now'"
    cf "alias em='sudo emerge'"
    cf "alias emp='sudo emerge -pv'"
    cf "alias ems='sudo emerge --sync'"
    cf "alias nn='sudo nano'"
    cf "alias mc='sudo nano /etc/portage/make.conf'"
    cf "alias pu='sudo nano /etc/portage/package.use'"
    cf "alias pm='sudo nano /etc/portage/package.mask'"
    cf "alias pk='sudo nano /etc/portage/package.keywords'"
    
    cp ${trg_file} /root/
    
    cf ""
    cf 'PS1="\n\[\e[32;1m\][\[\e[37;1m\]\u\[\e[32;1m\]][\[\e[34;1m\]\w\[\e[32;1m\]]$ \[\e[0m\]"'
    cf ""
    
    echo "" >> /root/.bashrc
    echo 'PS1="\n\[\e[31;1m\][\u][\[\e[34;1m\]\w\[\e[31;1m\]]$ \[\e[0m\]"' >> /root/.bashrc
    echo "" >> /root/.bashrc
    
    [[ ! -e /root/.bash_profile ]] && cp /etc/skel/.bash_profile /root/

    umrg "lafilefixer localepurge ntp"
    k_check
    end
}

end() {
    fl "/etc/portage/make.conf" "0" "0"

    avoid_dup 'FEATURES="-ccache -distcc fixlafiles parallel-fetch sandbox userpriv usersandbox"'
    
    sed -i -e '\!^FETCHCOMMAND=.*$!d' -e '\!^RESUMECOMMAND=.*$!d' ${trg_file}
    
    cl
    
    case ${keymap} in
    br)
        echo; eb2 "* "; eg2 "Removing all localization files excluding "; er2 "Portugese Brazilian"; eg "..."; sleep 1s; echo
    ;;
    trq|trf)
        echo; eb2 "* "; eg2 "Removing all localization files excluding "; er2 "Turkish"; eg "..."; sleep 1s; echo
    ;;
    us)
        echo; eb2 "* "; eg2 "Removing all localization files excluding "; er2 "English"; eg "..."; sleep 1s; echo
    ;;
    esac

    fl "/etc/locale.nopurge" "b" "d"
    
    cf "MANDELETE"
    cf "SHOWFREEDSPACE"
    cf "VERBOSE"
    cf ""
    
    case ${keymap} in
    br)
        cf "pt"
        cf "pt_BR"
        cf "pt_BR.UTF-8"
        cf "pt_BR ISO-8859-1"
    ;;
    trq|trf)
        cf "tr"
        cf "tr_TR"
        cf "tr_TR.UTF-8"
        cf "tr_TR ISO-8859-9"
    ;;
    us)
        cf "en"
        cf "en_US"
        cf "en_US.UTF-8"
        cf "en_US ISO-8859-1"
    ;;
    esac
    
    localepurge &>/dev/null

    cl
    
    [[ -z "${swap_part}" ]] && { swapoff /egswap &>/dev/null; rm -rf /egswap &>/dev/null; }
    
    echo; eb2 "* "; eg2 "Creating a small report at "; er2 "/home/${username}/report.txt"; eg "..."
    report
    
    er2 "* "; ey "Deleting temporary files..."; sleep 0.5s; echo
    
    rm -rf easygentoo.config *.DIGESTS *.eg *.md5sum *.tmp *.lst ${lt} ${vl} &>/dev/null
    mv *.tar.bz2 /home/${username}/ &>/dev/null
    mv ${eg} /home/${username}/ &>/dev/null
    mv ${profile} /home/${username}/ &>/dev/null
    mv ${compiled} /home/${username}/${compiled} &>/dev/null
    rm -rf /var/tmp/portage/* &>/dev/null

    chown -fPR ${username} /home/${username}/

    cl; eb2 "* "; ew "Setup has finished. Now your system is ready to use. Congratulations! :)"; echo; sleep 5s

    echo; ey2 "* "; er "Shutting down..."; echo; shutdown -h now
}

report() {
    rp="/home/${username}/report.txt"
    
    echo "Total installation time (uptime): $(uptime | tr ',' ' ' | awk '{print $3}')" >> ${rp}
    echo "Number of compiled packages: $(wc -l < ${compiled})" >> ${rp}
    echo "List of compiled packages: /home/${username}/${compiled}" >> ${rp}
    echo "Selected CPU architecture: ${arch}" >> ${rp}
    echo "Selected tarball: ${tarball}" >> ${rp}
    echo "Total CPU cores: ${core}" >> ${rp}
    echo "Total RAM: ${ram_size} KB" >> ${rp}
    echo "User: ${username}" >> ${rp}
    echo "User password: ${userpass}" >> ${rp}
    echo "Administrator (root) password: ${rootpass}" >> ${rp}
    echo "Domainname: ${domainname}" >> ${rp}
    echo "Hostname: ${hostname}" >> ${rp}
    
    case ${keymap} in
    br)
        echo "Keymap: br-abnt2" >> ${rp}
    ;;
    *)
        echo "Keymap: ${keymap}" >> ${rp}
    ;;
    esac
    
    if [ -n "${adapters_found}" ]; then
        echo "Network adapters: ${adapters_found}" >> ${rp}
    else
        echo "No network adapters were found." >> ${rp}
    fi
    echo "" >> ${rp}
    
    case ${blimit} in
    0)
        echo "No bandwidth limit is used during setup." >> ${rp}
    ;;
    *)
        echo "Bandwidth limit used during setup: ${blimit} KB/s" >> ${rp}
    ;;
    esac

    case ${setup} in
    basic)
        echo "Xfce is not installed." >> ${rp}
    ;;
    normal)
        echo "Xfce is installed as a desktop environment." >> ${rp}
    ;;
    esac
    
    echo "" >> ${rp}
    echo "Mirrors:" >> ${rp}
    
    for m in ${mirrorlist}
    do
        echo "    ${m}" >> ${rp}
    done
    
    echo "" >> ${rp}
    echo "Partitions used:" >> ${rp}

    if [ -n "${boot_part}" ]; then
        echo "    Partition: ${boot_part}, File System: ${boot_fs}" >> ${rp}
        echo "    Mount Point: ${boot_mp}, Label: ${boot_label}" >> ${rp}
        echo "" >> ${rp}
    fi

    if [ -n "${swap_part}" ]; then
        echo "    Partition: ${swap_part}, File System: ${swap_fs}" >> ${rp}
        echo "    Mount Point: ${swap_mp}, Label: ${swap_label}" >> ${rp}
        echo "" >> ${rp}
    fi

    if [ -n "${home_part}" ]; then
        echo "    Partition: ${home_part}, File System: ${home_fs}" >> ${rp}
        echo "    Mount Point: ${home_mp}, Label: ${home_label}" >> ${rp}
        echo "" >> ${rp}
    fi

    if [ -n "${root_part}" ]; then
        echo "    Partition: ${root_part}, File System: ${root_fs}" >> ${rp}
        echo "    Mount Point: ${root_mp}, Label: ${root_label}" >> ${rp}
        echo "" >> ${rp}
    fi

    if [ -e "extra.eg" ]; then
        while read name part label fs mp
        do
            echo "    Partition: ${part}, File System: ${fs}" >> ${rp}
            echo "    Mount Point: ${mp}, Label: ${label}" >> ${rp}
            echo "" >> ${rp}
        done < extra.eg
    fi
}

start

exit 0
